
mse.coords = JSON.parse('{"cid0":800,"cid1":500,"cid2":700,"cid3":50,"cid4":0,"cid5":8.3333333333333,"cid6":10.416666666667,"cid7":729.16666666667}');
initMseConfig();
mse.init();
var pages={};
var layers={};
var objs={};
var animes={};
var games={};
var wikis={};
function createbook(){
	mse.configs.srcPath='./six/';
	window.root = new mse.Root('six',mse.coor('cid0'),mse.coor('cid1'),'portrait');
	var temp = {};
	pages.sdfsd=new mse.BaseContainer(root,{size:[mse.coor('cid0'),mse.coor('cid1')]});
	layers.sdfsddefault=new mse.Layer(pages.sdfsd,1,{"globalAlpha":1,"textBaseline":"top","size":[mse.coor('cid0'),mse.coor('cid1')]});
	pages.sdfsd.addLayer('sdfsddefault',layers.sdfsddefault);
	layers.sdfsdfsdfd=new mse.ArticleLayer(pages.sdfsd,2,{"size":[mse.coor('cid2'),mse.coor('cid1')],"pos":[mse.coor('cid3'),mse.coor('cid4')],"globalAlpha":1,"font":"normal "+mse.coor('cid5')+"px Arial","textAlign":"left","textBaseline":"top","lineHeight":mse.coor('cid6')},null);
	objs.obj0=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'Nulla suscipit est id justo volutpat at mattis libero auctor. Cras non ipsum arcu, sed auctor tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis consectetur ',true); layers.sdfsdfsdfd.addObject(objs.obj0);
	objs.obj1=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'fermentum arcu sed venenatis. Vivamus vitae elit libero. Etiam mattis, nisi a facilisis mattis, augue mi luctus nunc, a mattis libero neque vulputate urna. Aliquam faucibus tellus at tellus interdum luctus. Vivamus ',true); layers.sdfsdfsdfd.addObject(objs.obj1);
	objs.obj2=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'non risus nisl. Cras non ipsum lacus, in fringilla nulla. Maecenas pretium sagittis augue, id pretium arcu accumsan ut. Cras et lorem non mi tristique blandit. Nulla augue velit, suscipit nec sodales sed, lacinia ',true); layers.sdfsdfsdfd.addObject(objs.obj2);
	objs.obj3=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'eget est. Curabitur in nisl vitae dolor faucibus adipiscing. Vivamus congue imperdiet mollis. Vivamus pretium, felis eget bibendum aliquam, libero orci adipiscing eros, at vehicula massa mauris sit amet nisl. ',true); layers.sdfsdfsdfd.addObject(objs.obj3);
	objs.obj4=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'Integer congue vehicula lacinia. Sed consequat laoreet bibendum. Integer eget urna lorem, eget interdum lacus. Sed porttitor neque a dui iaculis at volutpat diam suscipit. Etiam pharetra, eros et feugiat ',true); layers.sdfsdfsdfd.addObject(objs.obj4);
	objs.obj36=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',true); layers.sdfsdfsdfd.addObject(objs.obj36);
	objs.obj37=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid2'),mse.coor('cid6')]},' ringilla mollis dui, a porta ligula auctor ultricies. Duis eros velit, semper ac interdum faucibus, pulvinar quis est. Proin fringilla condimentum leo, in volutpat ipsum suscipit ',true);
	objs.obj5=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'pellentesque, purus metus placerat risus, vel interdum risus eros elementum lacus. Sed nunc purus, hendrerit at vulputate a, porta et purus. Aenean commodo, lacus id porta accumsan, odio felis sollicitudin nisl, ',true); layers.sdfsdfsdfd.addObject(objs.obj5);
	objs.obj6=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'convallis volutpat dui enim in dui. Cras consequat sem et velit pulvinar laoreet. Integer et viverra risus. Sed ut metus scelerisque erat accumsan sollicitudin nec sed odio. Nam euismod erat id quam rutrum ut ',true); layers.sdfsdfsdfd.addObject(objs.obj6);
	objs.obj7=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'venenatis purus rutrum. Suspendisse non eros at ligula placerat commodo ut ut est. Nullam fringilla sagittis tortor, non placerat leo dignissim eget. Cum sociis natoque penatibus et magnis dis parturient ',true); layers.sdfsdfsdfd.addObject(objs.obj7);
	objs.obj8=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'montes, nascetur ridiculus mus. Aliquam dui elit, tristique in aliquet vitae, cursus eget sapien. Curabitur feugiat mauris nec ipsum aliquet adipiscing eu non nisl. Fusce imperdiet sollicitudin nisl, id sodales nisi ',true); layers.sdfsdfsdfd.addObject(objs.obj8);
	objs.obj9=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'aliquet eu. Praesent a aliquam arcu. Etiam vel turpis non tortor hendrerit ullamcorper. Donec nec odio ac neque convallis laoreet. Vivamus eget ante nisi. Nunc ut eros magna. Vivamus suscipit fermentum tellus ',true); layers.sdfsdfsdfd.addObject(objs.obj9);
	objs.obj10=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'eu tincidunt. Suspendisse fringilla justo at libero auctor sit amet imperdiet leo rhoncus. Phasellus luctus, diam eu ultrices rhoncus, orci odio venenatis urna, vitae consequat nisl elit quis ipsum. Ut at mollis lorem. ',true); layers.sdfsdfsdfd.addObject(objs.obj10);
	objs.obj11=new mse.Text(layers.sdfsdfsdfd,{"size":[mse.coor('cid7'),mse.coor('cid6')]},'In id ligula ac odio molestie rhoncus et eget nisi.',true); layers.sdfsdfsdfd.addObject(objs.obj11);
	layers.sdfsdfsdfd.setDefile(1300);
	temp.layerDefile=layers.sdfsdfsdfd;
	pages.sdfsd.addLayer('sdfsdfsdfd',layers.sdfsdfsdfd);
	var action={};
	var reaction={};
	mse.currTimeline.start();};
mse.autoFitToWindow(createbook);