
mse.coords = JSON.parse('{"cid0":500,"cid1":400,"cid2":50,"cid3":0,"cid4":10,"cid5":333.33333333333,"cid6":355}');
initMseConfig();
mse.init();
var pages={};
var layers={};
var objs={};
var animes={};
var games={};
var wikis={};
function createbook(){
	mse.configs.srcPath='./proto/';
	window.root = new mse.Root('proto',mse.coor('cid0'),mse.coor('cid1'),'portrait');
	var temp = {};
	pages.dfgdf=new mse.BaseContainer(root,{size:[mse.coor('cid0'),mse.coor('cid1')]});
	layers.dfgdfdefault=new mse.Layer(pages.dfgdf,1,{"globalAlpha":1,"textBaseline":"top","size":[mse.coor('cid0'),mse.coor('cid1')]});
	pages.dfgdf.addLayer('dfgdfdefault',layers.dfgdfdefault);
	layers.dgdfgddd=new mse.ArticleLayer(pages.dfgdf,2,{"size":[mse.coor('cid1'),mse.coor('cid1')],"pos":[mse.coor('cid2'),mse.coor('cid3')],"globalAlpha":1,"font":"normal "+mse.coor('cid4')+"px Arial","textAlign":"left","textBaseline":"top","lineHeight":mse.coor('cid4')},null);
	objs.obj0=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',true); layers.dgdfgddd.addObject(objs.obj0);
	objs.obj1=new mse.Speaker( layers.dgdfgddd,{"size":[mse.coor('cid1'),mse.coor('cid3')]}, 'duis', null , mse.coor(mse.joinCoor(45)) , '#ABABAB' ); layers.dgdfgddd.addObject(objs.obj1);
	objs.obj2=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid6'),mse.coor('cid4')]},' lobortis auctor mattis. Donec suscipit semper tortor, quis aliquet lorem ',true);
	objs.obj1.addObject(objs.obj2);
	objs.obj3=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid6'),mse.coor('cid4')]},'laoreet vel. Aliquam ut nulla odio. Morbi vel urna mauris, ut varius nibh. ',true);
	objs.obj1.addObject(objs.obj3);
	objs.obj4=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid6'),mse.coor('cid4')]},'Donec id dolor dolor, vel sollicitudin lectus. Sed mi ante, luctus ut ',true);
	objs.obj1.addObject(objs.obj4);
	objs.obj5=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid6'),mse.coor('cid4')]},'commodo ut, pellentesque a tellus. Integer imperdiet dolor auctor tortor ',true);
	objs.obj1.addObject(objs.obj5);
	objs.obj6=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid6'),mse.coor('cid4')]},'auctor molestie. Nulla commodo risus sed libero sagittis scelerisque. ',true);
	objs.obj1.addObject(objs.obj6);
	objs.obj14=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'Quisque nunc orci, accumsan a vestibulum ut, facilisis ac erat. Praesent dui urna, ',true);
	objs.obj1.addObject(objs.obj14);
	objs.obj15=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'faucibus non dignissim sed, consectetur at sapien. Aliquam elementum lobortis nunc ',true);
	objs.obj1.addObject(objs.obj15);
	objs.obj16=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'a elementum. Vestibulum imperdiet nisl in sem pulvinar convallis. Maecenas semper ',true);
	objs.obj1.addObject(objs.obj16);
	objs.obj17=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'sem id lacus convallis id sagittis lorem tempus. Nulla rutrum, risus et imperdiet ',true);
	objs.obj1.addObject(objs.obj17);
	objs.obj18=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'sodales, lacus sem interdum magna, eget condimentum elit tellus vitae leo. Sed ',true);
	objs.obj1.addObject(objs.obj18);
	objs.obj19=new mse.Text(layers.dgdfgddd,{"size":[mse.coor('cid5'),mse.coor('cid4')]},'diam est, varius ac auctor sit amet, interdum at sem.',true);
	objs.obj1.addObject(objs.obj19);
	layers.dgdfgddd.setDefile(1300);
	temp.layerDefile=layers.dgdfgddd;
	pages.dfgdf.addLayer('dgdfgddd',layers.dgdfgddd);
	var action={};
	var reaction={};
	mse.currTimeline.start();};
mse.autoFitToWindow(createbook);