
mse.coords = JSON.parse('{"cid0":800,"cid1":600,"cid2":300,"cid3":200,"cid4":0,"cid5":15,"cid6":20,"cid7":375,"cid8":25}');
initMseConfig();
mse.init();
var pages={};
var layers={};
var objs={};
var animes={};
var games={};
var wikis={};
function createbook(){
	mse.configs.srcPath='./dialog/';
	window.root = new mse.Root('dialog',mse.coor('cid0'),mse.coor('cid1'),'portrait');
	var temp = {};
	pages.Dialog=new mse.BaseContainer(root,{size:[mse.coor('cid0'),mse.coor('cid1')]});
	layers.Dialogdefault=new mse.Layer(pages.Dialog,1,{"globalAlpha":1,"textBaseline":"top","size":[mse.coor('cid0'),mse.coor('cid1')]});
	pages.Dialog.addLayer('Dialogdefault',layers.Dialogdefault);
	layers.contenu=new mse.ArticleLayer(pages.Dialog,2,{"size":[mse.coor('cid2'),mse.coor('cid1')],"pos":[mse.coor('cid3'),mse.coor('cid4')],"globalAlpha":1,"font":"normal "+mse.coor('cid5')+"px ","textAlign":"left","textBaseline":"top","lineHeight":mse.coor('cid6')},null);
	objs.obj8=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',true); layers.contenu.addObject(objs.obj8);
	objs.obj9=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'Praesent rutrum imperdiet nisl, sed mollis quam scelerisque ',true); layers.contenu.addObject(objs.obj9);
	objs.obj13=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'interdum molestie, ipsum lectus pharetra justo, eget aliquet ',true); layers.contenu.addObject(objs.obj13);
	objs.obj55=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'gjdsog gdsjfshqfdh zeteza  zeta gsdqg sdfqgsdfg',true); layers.contenu.addObject(objs.obj55);
	objs.obj37=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'osigjsdùqz pa zro jezi jzlet',true); layers.contenu.addObject(objs.obj37);
	objs.obj56=new mse.Speaker(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]}, 'florent'); layers.contenu.addObject(objs.obj56);
	objs.obj57=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'omrz azorj azorpu razehtl gzhr ',true);
	objs.obj56.addObject(objs.obj57);
	objs.obj58=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'ezrpoiaz azoeiu azpei ',true);
	objs.obj56.addObject(objs.obj58);
	objs.obj59=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'gnfd;ngsdkflj  oqfsjql qikfhqf',true);
	objs.obj56.addObject(objs.obj59);
	objs.obj60=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'gnfd;ngsdkflj  oqfsjql qikfhqf',true);
	objs.obj56.addObject(objs.obj60);
	objs.obj61=new mse.UIObject(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]}); layers.contenu.addObject(objs.obj61);
	objs.obj62=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'gfdsijou peoir',true); layers.contenu.addObject(objs.obj62);
	objs.obj15=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'Fusce et mi nisi, non auctor lacus.',true); layers.contenu.addObject(objs.obj15);
	objs.obj19=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'hfdkjlshsd',true); layers.contenu.addObject(objs.obj19);
	objs.obj20=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'hgdfklhfd',true); layers.contenu.addObject(objs.obj20);
	objs.obj21=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'hjdfklh',true); layers.contenu.addObject(objs.obj21);
	objs.obj23=new mse.UIObject(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid6')]});
	objs.obj26=new mse.UIObject(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]}); layers.contenu.addObject(objs.obj26);
	objs.obj27=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'ghdfsjlh',true); layers.contenu.addObject(objs.obj27);
	objs.obj28=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'hdfsjhfdhfdhh',true); layers.contenu.addObject(objs.obj28);
	objs.obj29=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'salut salut salut',true); layers.contenu.addObject(objs.obj29);
	objs.obj17=new mse.Text(layers.contenu,{"size":[mse.coor('cid7'),mse.coor('cid8')]},'salut',true); layers.contenu.addObject(objs.obj17);
	layers.contenu.setDefile(1300);
	temp.layerDefile=layers.contenu;
	pages.Dialog.addLayer('contenu',layers.contenu);
	var action={};
	var reaction={};
	action.hfdh=new mse.Script([{src:objs.obj16,type:'click'}]);
	reaction.hfdh=function(){ 
		mse.setCursor('text'); 
	};
	action.hfdh.register(reaction.hfdh);
	mse.currTimeline.start();};
mse.autoFitToWindow(createbook);