var __currContextOwner__;
(function(i,g){var b=function(){};b.configs={font:"Verdana",srcPath:""};var h=b.configs;b.root=null;b.currTimeline=null;b.Ressource=function(){};b.Ressource.prototype={constructor:b.Ressource,list:{},loading:[],preload:[],loadInfo:"Chargement ressources: ",waitinglist:{},audExtCheck:/(.ogg|.mp3)/,init:function(){for(var a,c,b=0;12>b;b++){this.loading[b]=document.createElement("canvas");this.loading[b].width=300;this.loading[b].height=300;a=this.loading[b].getContext("2d");a.translate(150,150);c=2*
Math.PI/12;a.fillStyle="#AAAAAA";for(var e=0;12>e;e++)e==b?(a.fillStyle="#EEEEEE",a.fillRect(60,-9,60,18),a.fillStyle="#AAAAAA"):a.fillRect(60,-9,60,18),a.rotate(c)}},addSource:function(a,c,b,e){switch(b){case "img":case "image":this.list[a]=new Image;this.list[a].src=h.srcPath+c;this.list[a].lid=0;break;case "aud":case "audio":this.list[a]=document.createElement("audio");if(-1==c.search(this.audExtCheck))switch(MseConfig.browser){case "Chrome":case "Firefox":case "Opera":this.list[a].src=h.srcPath+
c+".ogg";break;case "Safari":case "Explorer":this.list[a].src=h.srcPath+c+".mp3"}else this.list[a].src=h.srcPath+c;this.list[a].load();break;default:return}this.list[a].type=b;e&&"aud"!=b&&"audio"!=b&&this.preload.push(this.list[a])},getSrc:function(a){a=this.list[a];if(!a)return null;switch(a.type){case "img":case "image":if(!a||a.complete)return a;12==a.lid&&(a.lid=0);return this.loading[a.lid++];case "aud":case "audio":return a}},waitSrc:function(a,c){if(this.list[a])if(this.list[a].complete)c.invoke();
else{this.waitinglist[a]||(this.waitinglist[a]=[]);var b=this.waitinglist[a];b.push(c);this.list[a].onload=function(){for(var a in b)b[a].invoke()}}},preloadProc:function(){for(var a=0,c=0;c<this.preload.length;c++)this.preload[c].complete&&a++;return[a,this.preload.length]},preloadPage:function(a,c,d){a.clearRect(0,0,b.root.width,b.root.height);a.save();a.strokeStyle="#333333";a.lineWidth=2;a.strokeRoundRect((b.root.width-280)/2,b.root.height-100,281,11,5);a.fillStyle="#555555";a.fillRoundRect((b.root.width-
280)/2,b.root.height-100,280*(c/d),10,5);c=this.loadInfo+c+"/"+d;d=a.measureText(c).width;a.font="20px "+h.font;a.fillStyle="#000000";a.fillText(c,(b.root.width-d)/2,b.root.height-60);a.restore()}};b.src=new b.Ressource;b.autoFitToWindow=function(a){a&&(i.autoFitCallback=a);coords&&coords.cid1&&!(250<MseConfig.pageHeight)&&setTimeout(b.autoFitToWindow,1E3)};b.init=function(a){g.extend(h,a);b.src.init();b.src.addSource("imgNotif","../images/turn_comp.png","img");b.src.addSource("fbBar","../images/barre/fb.png",
"img");b.src.addSource("wikiBar","../images/barre/wiki.png","img");b.src.addSource("wikiBn","../images/button/wiki.png","img");b.src.addSource("bookBn","../images/button/book.png","img");b.src.addSource("illuBn","../images/button/illu.png","img");b.src.addSource("audBn","../images/button/audIcon.png","img");b.src.addSource("accelerBn","../images/button/accelere.png","img",!0);b.src.addSource("upBn","../images/button/monter.png","img",!0);b.src.addSource("ralentiBn","../images/button/ralenti.png",
"img",!0);b.src.addSource("downBn","../images/button/descend.png","img",!0);b.src.addSource("playBn","../images/button/play.png","img",!0);b.src.addSource("pauseBn","../images/button/pause.png","img",!0);b.src.addSource("ratImg","../images/rat.png","img")};var m={fb:"rgb(74,108,164)",wiki:"rgb(230,82,82)",audio:"#FFB11B"},k={};b.fade=function(a,c,d,e,f){a&&(a=new b.KeyFrameAnimation(a,{frame:[0,c],opacity:[d,e]},1),f&&a.evtDeleg.addListener("end",f),a.start())};b.fadein=function(a,c,d){b.fade(a,c,
0,1,d)};b.fadeout=function(a,c,d){b.fade(a,c,1,0,d)};b.slidein=function(a,c,d,e,f){!a instanceof b.UIObject||(isNaN(f)&&(f=1),a=new b.KeyFrameAnimation(a,{frame:[0,c],pos:d,opacity:[0,f]},1),e&&a.evtDeleg.addListener("end",e),a.start())};b.slideout=function(a,c,d,e){!a instanceof b.UIObject||(a=new b.KeyFrameAnimation(a,{frame:[0,c],pos:d,opacity:[a.globalAlpha,0]},1),e&&a.evtDeleg.addListener("end",e,!1),a.start())};b.transition=function(a,c,d,e){var f=a.parent;f instanceof b.Layer&&f.insertBefore(c,
a);b.fadein(c,d,e);b.fadeout(a,d,new b.Callback(f.delObject,f,a))};b.setCursor=function(a){-1!=a.indexOf(".")?b.root.jqObj.css("cursor",'url("'+a+'"), auto'):b.root.jqObj.get(0).style.cursor=a};b.changePage=function(a,c){c&&a.evtDeleg.addListener("click",new b.Callback(b.root.transition,b.root,b.root.container),!0);b.root.transition(a)};b.createBackLayer=function(a){if(k[a])return k[a];var c=new b.Layer(null,0,{size:[b.root.width,b.root.height]});c.addObject(new b.Image(c,{size:[b.root.width,b.root.height]},
a));return k[a]=c};b.Callback=function(a,c){if(!a)return null;this.func=a;this.caller=c;if(2<arguments.length){this.args=[];for(var b=2;b<arguments.length;b++)this.args.push(arguments[b])}this.link=function(a){this.linked||(this.linked=[]);this.linked.push(a)};this.invoke=function(a){var b=null;this.args?b=a?this.args.concat(a):this.args:!this.args&&a&&(b=[a]);this.func.apply(c,b);if(this.linked)for(var d in this.linked)this.linked[d].invoke()}};b.EventListener=function(a,b,d,e){this.evtName=a;this.callback=
b;this.target=e?e:b.caller;this.preventBubbling=d?d:!1;this.inObj=function(a,b){return a&&b?this.target.inObj?this.target.inObj(a,b)?!0:!1:!0:!0};this.notify=function(a){this.callback.invoke(a)}};b.EventDelegateSystem=function(){function a(a,b){var e=a.target,f=b.target;return!e||!e.getZindex?-1:!f||!f.getZindex?1:e.getZindex()<f.getZindex()?1:e.getZindex()>f.getZindex()?-1:0}this.listeners={};this.domObj=null;this.setDominate=function(a){this.domObj=a};this.addListener=function(c,d,e,f){if("string"==
typeof c&&d){this.listeners[c]||(this.listeners[c]=[]);var j=!1,e=new b.EventListener(c,d,e,f),n=this.listeners[c],o;for(o in n)if(n[o].callback==d&&(!f||n[o].target==f))j=!0,n.splice(o,1,e);j||this.listeners[c].push(e);this.listeners[c].sort(a)}};this.removeListeners=function(a){delete this.listeners[a]};this.removeListener=function(a,b){var e=this.listeners[a];if(e)for(var f=0;f<e.length;f++)if(e[f].callback==b){e.splice(f,1);break}};this.eventNotif=function(a,b){var e=!1;switch(a){case "move":var f=
this.listeners.enter;if(f)for(var j in f)if(f[j].target.inObj(b.offsetX,b.offsetY)&&!f[j].target.inObj(b.prev[0],b.prev[1])){f[j].notify(b);e=!0;break}}if(f=this.listeners[a])for(var n in f){if((!this.domObj||this.domObj==f[n].target||this.domObj==f[n].target.parent)&&(!b||f[n].inObj(b.offsetX,b.offsetY))){var o=f[n].preventBubbling;f[n].notify(b);e=!0}if(o)break}return e}};b.EventDistributor=function(a,c,d){this.distributor=function(a){this.rootEvt.eventNotif(a.type,a);this.delegate&&this.delegate.eventNotif(a.type,
a)};this.setDelegate=function(a){this.delegate=a};this.src=a;c.mseInteraction(this);c.mseInteraction("setDelegate",this.distributor);this.rootEvt=new b.EventDelegateSystem;d&&this.setDelegate(d);this.setDominate=function(a){this.rootEvt.setDominate(a);this.delegate&&this.delegate.setDominate(a)};this.addListener=function(a,b,c,d){this.rootEvt.addListener(a,b,c,d)};this.removeListeners=function(a){this.rootEvt.removeListeners(a)};this.removeListener=function(a,b){this.rootEvt.removeListener(a,b)}};
b.Link=function(a,b,d,e,f,j){this.src=a;this.index=b;this.type=d;this.link=e;switch(this.type){case "fb":this.image="fbBar";break;case "wiki":this.image="wikiBar";break;case "illu":this.width=f?f:300,this.height=j?j:400}};b.UIObject=function(a,c){a?(this.parent=a,this.fixed=!1):this.parent=null;this.evtDeleg=new b.EventDelegateSystem;if(c&&(c.pos&&this.setPos(c.pos[0],c.pos[1]),c.size&&this.setSize(c.size[0],c.size[1]),c.font&&(this.font=c.font),c.fillStyle&&(this.fillStyle=c.fillStyle),c.strokeStyle&&
(this.strokeStyle=c.strokeStyle),this.globalAlpha=isNaN(c.globalAlpha)?1:c.globalAlpha,c.lineWidth&&(this.lineWidth=c.lineWidth),c.shadow&&(this.shadow=c.shadow),c.textAlign&&(this.textAlign=c.textAlign),c.textBaseline&&(this.textBaseline=c.textBaseline),c.insideRec))this.insideRec=c.insideRec};b.UIObject.prototype={offx:0,offy:0,width:0,height:0,fixed:!0,setPos:function(a,b,d){d?(this.offx=a+(this.fixed?d.getX():d.offx),this.offy=b+(this.fixed?d.getY():d.offy)):(this.offx=a,this.offy=b)},setX:function(a,
b){this.offx=b?a+(this.fixed?b.getX():b.offx):a},setY:function(a,b){this.offy=b?a+(this.fixed?b.getY():b.offy):a},getX:function(){return this.parent?this.parent.getX()+this.offx:this.offx},getY:function(){return this.parent?this.parent.getY()+this.offy:this.offy},getCanvasX:function(){if(this.parent)return this.parent.getCanvasX()+this.offx;var a=0;b.root.viewport&&(a=-b.root.viewport.x);return a+this.offx},getCanvasY:function(){if(this.parent)return this.parent.getCanvasY()+this.offy;var a=0;b.root.viewport&&
(a=-b.root.viewport.y);return a+this.offy},setSize:function(a,b){this.width=a;this.height=b},getWidth:function(){return this.width},getHeight:function(){return this.height},inObj:function(a,b){if(1>this.getAlpha())return!1;if(this.insideRec)var d=this.getCanvasX()+this.insideRec[0],e=this.getCanvasY()+this.insideRec[1],f=this.insideRec[2],j=this.insideRec[3];else d=this.getCanvasX(),e=this.getCanvasY(),f=this.getWidth(),j=this.getHeight();return a>d&&a<d+f&&b>e&&b<e+j?!0:!1},getZindex:function(){return this.zid?
this.zid:this.parent?this.parent.zid:0},getContainer:function(){return this instanceof b.BaseContainer?this:this.parent?this.parent.getContainer():b.root.container},setAlpha:function(a){this.globalAlpha=a},getAlpha:function(){return this.parent?this.parent.getAlpha()*this.globalAlpha:this.globalAlpha},getScale:function(){return isNaN(this.scale)?this.parent?this.parent.getScale():1:this.parent?this.parent.getScale()*this.scale:this.scale},move:function(a,b){this.offx+=a;this.offy+=b},addListener:function(){this.evtDeleg.addListener.apply(this.evtDeleg,
arguments)},removeListener:function(){this.evtDeleg.removeListener.apply(this.evtDeleg,arguments)},configCtxFlex:function(a){this.font&&(a.font=this.font);this.fillStyle&&(a.fillStyle=this.fillStyle);this.strokeStyle&&(a.strokeStyle=this.strokeStyle);this.lineWidth&&(a.lineWidth=this.lineWidth);this.shadow?(a.shadowOffsetX=this.shadow.shadowOffsetX,a.shadowOffsetY=this.shadow.shadowOffsetY,a.shadowBlur=this.shadow.shadowBlur,a.shadowColor=this.shadow.shadowColor):a.shadowOffsetX=a.shadowOffsetY=a.shadowBlur=
0;this.textAlign&&(a.textAlign=this.textAlign);this.textBaseline&&(a.textBaseline=this.textBaseline);a.globalAlpha=this.getAlpha()},configCtx:function(a){a.restore();a.save();this.configCtxFlex(a);var b=this.getScale();1!=b&&a.scale(b,b)},draw:function(){},logic:function(){},toString:function(){return"[object MseUIObject]"}};b.Root=function(a,c,d){this.setPos=function(a,b){this.jqObj.css({left:a+"px",top:b+"px"})};this.setSize=function(a,b){this.width=a;this.height=b;this.jqObj.attr({width:a,height:b})};
this.setScale=function(a){if(1<a){this.height*a>MseConfig.pageHeight&&(a=MseConfig.pageHeight/this.height);this.width*a>MseConfig.pageWidth&&(a=MseConfig.pageWidth/this.width);var b=this.width*a,c=this.height*a;this.setPos((MseConfig.pageWidth-b)/2,(MseConfig.pageHeight-c)/2);this.setSize(b,c);this.scale=a}};this.setCenteredViewport=function(){this.viewport={};this.viewport.x=(this.width-MseConfig.pageWidth)/2;this.viewport.y=(this.height-MseConfig.pageHeight)/2;this.jqObj.attr({width:MseConfig.pageWidth,
height:MseConfig.pageHeight});this.jqObj.css({left:"0px",top:"0px"});this.ctx.translate(-this.viewport.x,-this.viewport.y)};this.setContainer=function(a){this.container&&(this.container.firstShow=!1);a.root=this;this.container=a;this.evtDistributor.setDelegate(a.evtDeleg);this.dest=null;this.container.scale=this.scale};this.transition=function(a){this.dest||(this.container?(b.fadeout(this.container,20,new b.Callback(this.setContainer,this,a)),this.dest=a):this.setContainer(a),b.fadein(a,20))};this.inObj=
function(){return!0};this.logic=function(a){for(var b in this.animations)this.animations[b].logic(a)&&this.animations.splice(b,1);var c=!1;for(b in this.animes)this.animes[b].logic(a),this.animes[b].block&&(c=!0);c||this.gamewindow.logic(a)||this.container&&this.container.logic(a)};this.draw=function(){MseConfig.mobile?this.ctx.clearRect(0,0,MseConfig.pageWidth,MseConfig.pageHeight):this.ctx.clearRect(0,0,this.width,this.height);if(!MseConfig.mobile||!(this.gamewindow.currGame&&"INDEP"==this.gamewindow.currGame.type))this.container&&
this.container.draw(this.ctx),this.dest&&this.dest.draw(this.ctx);this.gamewindow.currGame&&this.gamewindow.draw(this.ctx);for(var a in this.animes)this.animes[a].draw(this.ctx)&&this.animes.splice(a,1);this.evtDistributor.rootEvt.eventNotif("drawover",this.ctx)};this.initTimeline=function(){};this.runTimeline=function(a){this.init?this.end?b.currTimeline.end=!0:(this.logic(a),this.draw()):(a=b.src.preloadProc(),a[0]<a[1]?b.src.preloadPage(this.ctx,a[0],a[1]):this.init=!0)};b.root=this;this.jqObj=
g("<canvas></canvas>");this.jqObj.attr({id:a});a=(MseConfig.pageWidth-c)/2;this.jqObj.css({margin:"0px auto",padding:"0px",position:"absolute",left:a+"px",top:"0px"});g("body").css({position:"relative"}).append(this.jqObj);this.scale=1;this.setSize(c,d);this.interval=40;this.ctx=this.jqObj.get(0).getContext("2d");MseConfig.mobile&&(this.setCenteredViewport(),g(i).bind("orientationchange",function(){b.root.setCenteredViewport()}));this.evtDistributor=new b.EventDistributor(this,this.jqObj);this.container=
null;this.init=this.end=!1;this.animations=[];this.animes=[];var e=g('<div id="video">');e.css({position:"absolute",width:0.8*c+"px",height:0.8*d+"px",left:a+0.1*c+"px",top:0.1*d+"px"});g("body").prepend(e);this.video=e.flareVideo(g("body"));this.video.hide();this.gamewindow=new b.GameShower;b.currTimeline=new b.Timeline(this,this.interval)};b.BaseContainer=function(a,c,d){b.UIObject.call(this,null,c);this._layers=[];this._changed=[];this.deleg=null;this.scale=1;this.count=0;this.firstShow=!1;MseConfig.mobile?
(this.orientation=MseConfig.orientation,this.normal=!0,this.setOrientation(d?d:"portrait")):this.normal=!0;a&&a.setContainer(this)};extend(b.BaseContainer,b.UIObject);g.extend(b.BaseContainer.prototype,{setOrientation:function(a){MseConfig.mobile&&!("landscape"!=a&&"portrait"!=a)&&(this.orientation=a)},orientChange:function(a){__currContextOwner__=b.root;this.normal=a==this.orientation?!0:!1;b.root.jqObj.attr({width:MseConfig.pageWidth,height:MseConfig.pageHeight});b.root.width=MseConfig.pageWidth;
b.root.height=MseConfig.pageHeight},addLayer:function(a,c){null!=a&&c instanceof b.UIObject&&(c.name=a,this._layers.push(c),this.sortLayer())},delLayer:function(a){if(null!=a)for(var b in this._layers)this._layers[b].name==a&&this._layers.splice(b,1)},getLayer:function(a){if(null!=a)for(var b in this._layers)if(this._layers[b].name==a)return this._layers[b]},sortLayer:function(){this._layers.sort(function(a,b){return a.zid<b.zid?-1:a.zid>b.zid?1:0})},setLayerActivate:function(a,b){null!=a&&null!=
this._layers[a]&&this._layers[a].setActivate(b)},desactiveOthers:function(a){for(var b in this._layers)this._layers[b].active&&this._layers[b].name!=a&&(this._layers[b].setActivate(!1),this._changed.push(b))},reactiveOthers:function(){for(var a=this._changed.length,b=0;b<a;b++)this._layers[this._changed.pop()].setActivate(!0)},logic:function(a){if(!this.firstShow){this.firstShow=!0;this.evtDeleg.eventNotif("show");for(var b in this._layers)this._layers[b].evtDeleg.eventNotif("show")}MseConfig.mobile&&
(this.normal&&MseConfig.orientation!=this.orientation?this.orientChange(MseConfig.orientation):!this.normal&&MseConfig.orientation==this.orientation&&this.orientChange(MseConfig.orientation));if(this.normal)if(this.deleg)this.deleg.logic(a);else for(b in this._layers)this._layers[b].logic(a);this.count++},draw:function(a){if(this.normal)if(this.deleg)this.deleg.draw(a);else{this.configCtx(a);for(var c in this._layers)this._layers[c].draw(a)}else a.drawImage(b.src.getSrc("imgNotif"),(a.canvas.width-
50)/2,(a.canvas.height-80)/2,50,80)},toString:function(){return"[object MseBaseContainer]"}});b.Layer=function(a,c,d){b.UIObject.call(this,a,d);this.zid=c;this.active=!0;this.objList=[]};extend(b.Layer,b.UIObject);g.extend(b.Layer.prototype,{getObjectIndex:function(a){if(this.objList.indexOf)var b=this.objList.indexOf(a);else for(var d in this.objList)if(this.objList[d]===a){b=d;break}return null!=b&&-1!=b?b:-1},addObject:function(a){return a instanceof b.UIObject?(this.objList.push(a),!0):!1},insertObject:function(a,
c){return a instanceof b.UIObject&&0<=c&&c<this.objList.length?(this.objList.splice(c,0,a),!0):!1},insertBefore:function(a,b){var d=this.getObjectIndex(b);-1!=d&&this.insertObject(a,d)},insertAfter:function(a,b){var d=this.getObjectIndex(b);-1!=d&&(d+1==this.objList.length?this.addObject(a):this.insertObject(a,d+1))},delObject:function(a){if(isNaN(a)){if(a instanceof b.UIObject){if(this.objList.indexOf)var c=this.objList.indexOf(a);else for(var d in this.objList)if(this.objList[d]===a){c=d;break}return null!=
c&&-1!=c?(this.objList.splice(c,1),c):!1}}else return this.objList.splice(a,1),a},delAll:function(){for(var a in this.objList)delete this.objList[a];this.objList.length=0},getObject:function(a){return 0<=a&&a<this.objList.length?this.objList[a]:null},delSelf:function(){this.parent instanceof b.BaseContainer&&this.parent.delLayer(this.name)},setActivate:function(a){this.active=a},logic:function(a){if(this.active)for(var b=0;b<this.objList.length;b++)this.objList[b].logic(a)},draw:function(a){this.configCtx(a);
for(var b=0;b<this.objList.length;b++)this.objList[b].draw(a)}});b.Text=function(a,c,d,e){b.UIObject.call(this,a,c);this.text=d;this.styled=e?!0:!1;this.linkInit=!1;this.zid=12;this.currentEffect=null;this.firstShow=!1;this.addLink=function(a){switch(a.type){case "audio":this.evtDeleg.addListener("firstShow",new b.Callback(a.link.play,a.link));this.getContainer().evtDeleg.addListener("click",new b.Callback(a.link.play,a.link),!0,this);break;case "wiki":this.getContainer().evtDeleg.addListener("click",
new b.Callback(a.link.init,a.link,this.getContainer()),!0,this);break;case "fb":this.getContainer().evtDeleg.addListener("click",new b.Callback(i.open,i,a.link,"_newtab"),!0,this)}a.offset=this.text.indexOf(a.src);a.owner=this;this.link=a};this.startEffect=function(a){this.styled=!0;b.initTextEffect&&(this.currentEffect=b.initTextEffect(a,this))};this.endEffect=function(){this.currentEffect=null};this.inObj=function(a,b){return this.link?a>=this.getCanvasX()+this.linkOffs&&a<=this.getCanvasX()+this.endOffs+
20&&b>=this.getCanvasY()&&b<=this.getCanvasY()+20?!0:!1:this.constructor.prototype.inObj.call(this,a,b)};this.logic=function(a){null!=this.currentEffect&&this.currentEffect.logic(a)};this.draw=function(a,b,c){this.firstShow||(this.firstShow=!0,this.evtDeleg.eventNotif("firstShow"));null!=b&&null!=c&&this.setPos(b,c);b=[this.getX(),this.getY()];this.styled&&(a.save(),this.configCtxFlex(a));null!=this.currentEffect?this.currentEffect.draw(a):this.link&&0<=this.link.offset?(this.linkInit||(this.begin=
this.text.substring(0,this.link.offset),this.linkOffs=a.measureText(this.begin).width,this.endOffs=this.linkOffs+a.measureText(this.link.src).width,this.end=this.text.substr(this.link.offset+this.link.src.length),"audio"==this.link.type&&this.evtDeleg.removeListener("show",this.link.link.play),this.linkInit=!0),a.fillText(this.begin,b[0],b[1]),a.save(),a.fillStyle=m[this.link.type],a.fillText(this.link.src,b[0]+this.linkOffs,b[1]),a.restore(),a.fillText(this.end,b[0]+this.endOffs,b[1])):a.fillText(this.text,
b[0],b[1]);this.styled&&a.restore()}};extend(b.Text,b.UIObject);b.Text.prototype.toString=function(){return"[object mse.Text]"};b.ArticleLayer=function(a,c,d,e){b.Layer.call(this,a,c,d);this.setDefile=function(a){this.currIndex=this.currTime=0;this.interval=a;this.complete=!1;this.endId=0;this.setSlider();this.ctrUI=new b.UIObject(null,{pos:[this.getX()+50,b.root.height-45],size:[this.width-100,50]});this.ctrUI.accelere=new b.Image(null,{size:[30,30]},"accelerBn");this.ctrUI.ralenti=new b.Image(null,
{size:[30,30]},"ralentiBn");this.ctrUI.up=new b.Image(null,{size:[30,30]},"upBn");this.ctrUI.down=new b.Image(null,{size:[30,30]},"downBn");this.ctrUI.play=new b.Image(null,{size:[30,30]},"playBn");this.ctrUI.pause=new b.Image(null,{size:[30,30]},"pauseBn");this.ctrUI.tip=new b.Text(null,{textBaseline:"middle",textAlign:"center",font:"italic 20px "+h.font,fillStyle:"#FFF"},"",!0);this.ctrUI.layer=this;this.ctrUI.draw=function(a){a.save();a.translate(this.offx,this.offy);this.accelere.draw(a,this.width-
30,0);this.up.draw(a,this.width-70,0);this.layer.pause?this.play.draw(a,this.width/2-15,0):this.pause.draw(a,this.width/2-15,0);this.ralenti.draw(a,0,0);this.down.draw(a,40,0);a.restore();this.tip.draw(a)};this.ctrEffect=function(a){var c=0,d=0;b.root.viewport&&(c=b.root.viewport.x,d=b.root.viewport.y);var e=c+a.offsetX-this.ctrUI.offx,f=d+a.offsetY-this.ctrUI.offy;if(!(0>f||50<f)){if(0<=e&&30>=e)this.interval+=200,this.interval=2E3<this.interval?2E3:this.interval,this.ctrUI.tip.text="moins rapide";
else if(e>=this.width-130&&e<=this.width-100)this.interval-=200,this.interval=300>this.interval?300:this.interval,this.ctrUI.tip.text="plus rapide";else if(e>=this.ctrUI.width/2-15&&e<=this.ctrUI.width/2+15)this.pause=!this.pause,this.ctrUI.tip.text=this.pause?"pause":"reprendre";else return;this.ctrUI.tip.globalAlpha=1;b.slideout(this.ctrUI.tip,10,[[a.offsetX+c,a.offsetY+d],[a.offsetX+c,a.offsetY+d-50]])}};this.upDownStart=function(a){var c=0;b.root.viewport&&(c=b.root.viewport.x);a=c+a.offsetX-
this.ctrUI.offx;40<=a&&70>=a?this.scrollEvt.rolled=-10:a>=this.width-170&&a<=this.width-140&&(this.scrollEvt.rolled=10)};this.upDownEnd=function(){this.scrollEvt.rolled=0};a=new b.Callback(this.ctrEffect,this);this.getContainer().evtDeleg.addListener("click",a,!0,this.ctrUI);this.getContainer().evtDeleg.addListener("gestureStart",new b.Callback(this.upDownStart,this),!0,this.ctrUI);this.getContainer().evtDeleg.addListener("gestureEnd",new b.Callback(this.upDownEnd,this));this.speedCtr=function(a){switch(a.keyCode){case __KEY_LEFT:this.interval+=
100;this.interval=2E3<this.interval?2E3:this.interval;break;case __KEY_RIGHT:this.interval-=100,this.interval=300>this.interval?300:this.interval}};a=new b.Callback(this.speedCtr,this);this.getContainer().evtDeleg.addListener("keydown",a)};this.setSlider=function(){this.slider=new b.Slider(this,{},"vertical");this.updateListScreen();this.slider.evtDeleg.addListener("rolling",new b.Callback(function(){this.pause=!0},this));this.slider.evtDeleg.addListener("hide",new b.Callback(function(){var a=this.complete?
this.objList.length:this.currIndex;if(0==a||this.objList[a-1].getY()<0.55*b.root.height)this.pause=!1},this))};this.updateIndexs=function(a,b){for(var c in this.phraseIndexs)this.phraseIndexs[c]>=a&&(this.phraseIndexs[c]+=b)};this.setLinklist=function(a){for(var b in a)for(var c=a[b].index,d=this.phraseIndexs[c];d<this.phraseIndexs[c+1];d++)if(this.objList[d].text&&0<=this.objList[d].text.indexOf(a[b].src)){a[b].index=d;this.objList[d].addLink(a[b]);break}this.links=a};this.setLinkDelegate=function(a,
c){if(this.links)for(var d in this.links)this.links[d].type==c&&(this.objList[this.links[d].index].evtDeleg.addListener("show",new b.Callback(a.linkShowHandler,a,this.links[d])),this.objList[this.links[d].index].evtDeleg.addListener("disapear",new b.Callback(a.linkDisapearHandler,a,this.links[d])))};this.addObject=function(a){var b=this.objList.length-1;0<=b?a.setY(this.objList[b].height,this.objList[b]):a.setY(0);this.length+=a.height;this.endId=this.objList.length-1;return this.constructor.prototype.addObject.call(this,
a)};this.addGame=function(a){a=new b.GameExpose(this,{size:[0.8*this.width,0.65*this.width]},a);a.setX(0.1*this.width);this.addObject(a)};this.insertObject=function(a,b){var c=this.constructor.prototype.insertObject.call(this,a,b);if(!c)return c;this.updateIndexs(b,1);0==b&&(a.setY(0),b=1);for(var d=b;d<this.objList.length;d++)this.objList[d].setY(this.objList[d-1].height,this.objList[d-1]);this.length+=a.height;return c};this.insertGame=function(a,c){var d=new b.GameExpose(this,{size:[0.8*this.width,
0.65*this.width]},a);d.setX(0.1*this.width);this.insertObject(d,c)};this.delObject=function(a){var b=this.constructor.prototype.delObject.call(this,a);isNaN(b)||(this.length-=a.height,this.updateIndexs(b,-1),this.endId=this.objList.length-1);return b};this.getHeight=function(){var a=this.complete?this.objList.length:this.currIndex;return 0==a?0:this.objList[a-1].offy+this.objList[a-1].height};this.updateListScreen=function(){var a=this.oy-this.offy,a=0>a?0:a,b=a+0.8*this.height,c=this.complete?this.objList.length-
1:this.currIndex-1,c=0>c?0:c,d=-1,e=-1;if(this.prevOffy<=a){for(var f=this.startId;f<=c;f++)if(-1==d&&this.objList[f].offy+this.objList[f].height>a&&(d=f),-1==e&&this.objList[f].offy>b){e=f;break}d=-1==d?c:d;e=-1==e?c:e}else{for(f=this.endId;0<=f;f--)if(-1==e&&this.objList[f].offy<=b&&(e=f),-1==d&&this.objList[f].offy+this.objList[f].height<=a){d=f;break}d=-1==d?0:d;e=-1==e?0:e}if(d>this.startId)for(f=this.startId;f<d;f++)this.objList[f].evtDeleg.eventNotif("disapear");else if(d<this.startId)for(f=
d;f<this.startId;f++)this.objList[f].evtDeleg.eventNotif("show");if(e>this.endId)for(f=this.endId+1;f<=e;f++)this.objList[f].evtDeleg.eventNotif("show");else if(e<this.endId)for(f=e+1;f<=this.endId;f++)this.objList[f].evtDeleg.eventNotif("disapear");this.startId=d;this.endId=e};this.logic=function(a){if(this.active&&this.dominate instanceof b.UIObject)this.dominate.logic(a);else{this.scrollEvt.rolled&&this.slider.scroll(this.scrollEvt);this.slider&&this.updateListScreen();for(var c=this.startId;c<=
this.endId;c++)this.objList[c].logic(a);if(!this.complete&&this.active&&!this.pause&&(this.currTime+=a,this.currTime>=(0!=this.currIndex&&this.objList[this.currIndex-1]instanceof b.Image?3E3:this.interval)))this.currTime=0,this.currIndex<this.objList.length?(a=this.objList[this.currIndex].offy+this.objList[this.currIndex].height/2,a>b.root.height/2&&(new b.KeyFrameAnimation(this,{frame:[0,15],pos:[[this.offx,this.offy],[this.offx,this.height/2-a]]},1)).start(),this.currIndex++):this.complete=!0;this.prevOffy=
0>this.oy-this.offy?0:this.oy-this.offy}};this.draw=function(a){this.configCtx(a);for(var b=this.startId;b<=this.endId;b++)this.objList[b].draw(a);this.ctrUI&&this.ctrUI.draw(a)};this.inObj=function(a,b){return this.parent.inObj(a,b)};this.interrupt=function(){this.dominate=this.vide};this.play=function(){this.dominate=null};this.length=0;this.prevOffy=this.oy=this.offy;this.lineHeight=d.lineHeight?d.lineHeight:Math.round(1.4*(this.font?checkFontSize(this.font):16));this.phraseIndexs=[];if(e){a=b.root.ctx;
this.configCtx(a);for(var c=Math.floor(this.width/a.measureText("A").width),e=e.split("\n"),f=d=0;f<e.length;f++)if(0==e[f].length)this.addObject(new b.UIObject(this,{size:[this.width,15]})),d++;else{this.phraseIndexs[f-d]=this.objList.length;for(var j=0;j<e[f].length;){var g=checkNextLine(a,e[f].substr(j),c,this.width);this.addObject(new b.Text(this,{size:[this.width,this.lineHeight]},e[f].substr(j,g)));j+=g}}}this.startId=0;this.endId=this.objList.length-1;this.complete=!0;this.pause=!1;this.scrollEvt=
{};this.scrollEvt.rolled=0;this.vide=new b.UIObject;this.dominate=null};extend(b.ArticleLayer,b.Layer);b.Image=function(a,c,d){b.UIObject.call(this,a,c);this.img=d;this.currentEffect=null;this.firstShow=!1;b.src.waitSrc(this.img,new b.Callback(this.init,this))};extend(b.Image,b.UIObject);g.extend(b.Image.prototype,{init:function(){if(!this.width){var a=b.src.getSrc(this.img);this.width=a.width;this.height=a.height}},startEffect:function(a){b.initImageEffect&&(this.currentEffect=b.initImageEffect(a,
this))},endEffect:function(){this.currentEffect=null},logic:function(a){this.firstShow||(this.firstShow=!0,this.evtDeleg.eventNotif("firstShow"));null!=this.currentEffect&&this.currentEffect.logic(a)},draw:function(a,c,d){var e=b.src.getSrc(this.img);this.configCtxFlex(a);if(isNaN(c)||isNaN(d))c=this.getX(),d=this.getY();null!=this.currentEffect?this.currentEffect.draw(a,c,d):a.drawImage(e,c,d,this.width,this.height)},toString:function(){return"[object mse.Image]"}});b.Mask=function(a,c,d){b.UIObject.call(this,
a,c);null!=d&&(this.zid=d);c.cornerRatio&&(this.cr=c.cornerRatio);this.draw=function(a){this.configCtxFlex(a);this.cr?a.fillRoundRect(this.getX(),this.getY(),this.width,this.height,this.cr):a.fillRect(this.getX(),this.getY(),this.width,this.height)}};b.Mask.prototype=new b.UIObject;b.Mask.prototype.constructor=b.Mask;b.Sprite=function(a,c,d,e,f,j,h,g,i){b.Image.call(this,a,c,d);if(4==arguments.length)this.frames=e;else if(this.fw=e,this.fh=f,9==arguments.length?(this.sx=j,this.sy=h,this.sw=g,this.sh=
i):(this.sy=this.sx=0,this.sw=this.img.width,this.sh=this.img.height),e<this.sw?this.col=Math.floor(this.sw/e):(this.fw=this.sw,this.col=1),f<this.sh?this.row=Math.floor(this.sh/f):(this.fh=this.sh,this.row=1),this.nb=this.col*this.row,0==this.width&&(this.width=this.fw),0==this.height)this.height=this.fh;this.curr=0};extend(b.Sprite,b.Image);g.extend(b.Sprite.prototype,{init:function(){},appendFrames:function(a){this.frames&&(this.frames=this.frames.concat(a))},appendFrame:function(a){this.frames&&
this.frames.push(a)},draw:function(a,c,d){this.configCtxFlex(a);isNaN(c)&&(c=this.getX());isNaN(d)&&(d=this.getY());var e=b.src.getSrc(this.img);if(this.frames)f=this.frames[this.curr][0],j=this.frames[this.curr][1],a.drawImage(e,f,j,this.frames[this.curr][2],this.frames[this.curr][3],c,d,this.getWidth(),this.getHeight());else{var f=this.sx+this.curr%this.col*this.fw,j=this.sy+Math.floor(this.curr/this.col)*this.fh;a.drawImage(e,f,j,this.fw,this.fh,c,d,this.getWidth(),this.getHeight())}}});b.Game=
function(){b.UIObject.call(this,null,{});this.offx=0.2*b.root.width;this.offy=0.2*b.root.height;this.width=0.6*b.root.width;this.height=0.6*b.root.height;this.type="DEP"};extend(b.Game,b.UIObject);g.extend(b.Game.prototype,{state:"DEFAULT",msg:{DEFAULT:"C'est un jeu, sans message......"},getMsg:function(){return this.msg[this.state]},setExpose:function(a){this.expo=a;this.type="INDEP"},addTo:function(a){this.parent=a;this.setPos(0,0);this.setSize(a.getWidth(),a.getHeight());a.addObject(this)},start:function(){b.root.container.evtDeleg.setDominate(this);
b.root.gamewindow.loadandstart(this)},draw:function(){},end:function(){b.root.gamewindow.end();this.expo&&this.expo.endGame()},lose:function(){b.root.gamewindow.lose()}});b.GameShower=function(){b.UIObject.call(this,null,{});this.currGame=null;this.globalAlpha=0;this.state="DESACTIVE";b.src.addSource("gameover","../images/gameover.jpg","img",!0);this.loseimg=new b.Image(this,{pos:[0,0]},"gameover");this.losetext=new b.Text(this,{font:"Bold 36px "+b.configs.font,fillStyle:"#FFF",textBaseline:"middle",
textAlign:"center"},"GAME OVER...",!0);this.losetext.evtDeleg.addListener("show",new b.Callback(this.losetext.startEffect,this.losetext,{typewriter:{speed:2}}));this.passBn=new b.Button(this,{size:[105,35],font:"12px "+h.font,fillStyle:"#FFF"},"Je ne joue plus","aideBar");this.firstShow=!1;this.load=function(a){a&&a instanceof b.Game&&(this.currGame=a,this.firstShow=!1,this.state="LOAD",b.fadein(this,15),b.fadein(this.currGame,15))};this.start=function(){this.currGame&&(this.setPos(this.currGame.offx,
this.currGame.offy),this.setSize(this.currGame.width,this.currGame.height),this.loseimg.setSize(this.width-5,this.height-5),this.losetext.setPos(this.width/2,this.height/2),this.passBn.setPos(this.currGame.width-115,this.currGame.height-50),this.currGame.init&&this.currGame.init(),this.state="START")};this.loadandstart=function(a){this.load(a);this.start()};this.restart=function(c){b.root.evtDistributor.removeListener("click",a);this.passBn.inObj(c.offsetX,c.offsetY)?this.currGame.end():(this.state=
"START",this.currGame.init())};var a=new b.Callback(this.restart,this);this.lose=function(){this.state="LOSE";this.losetext.evtDeleg.eventNotif("show");b.root.evtDistributor.addListener("click",a,!0,this.currGame)};this.end=function(){b.fadeout(this.currGame,25);b.fadeout(this,25,this.cbdesact)};this.desactive=function(){this.state="DESACTIVE";b.root.evtDistributor.setDominate(null)};this.cbdesact=new b.Callback(this.desactive,this);this.logic=function(a){"LOSE"==this.state&&this.losetext.logic();
if("START"!=this.state&&"LOAD"!=this.state)return!1;MseConfig.mobile&&"landscape"!=MseConfig.orientation||this.currGame.logic(a);return!0};this.draw=function(a){0!=this.globalAlpha&&((this.configCtx(a),MseConfig.mobile||(a.strokeStyle="rgb(188,188,188)",a.lineWidth=5,a.strokeRect(this.offx-2.5,this.offy-2.5,this.width,this.height),a.lineWidth=1),"INDEP"==this.currGame.type&&MseConfig.mobile&&"landscape"!=MseConfig.orientation)?a.drawImage(b.src.getSrc("imgNotif"),(a.canvas.width-50)/2,(a.canvas.height-
80)/2,50,80):"START"==this.state?(this.firstShow||(this.firstShow=!0,"INDEP"==this.currGame.type&&this.evtDeleg.eventNotif("firstShow"),MseConfig.mobile&&(this.currGame.setPos(0,0),this.currGame.setSize(MseConfig.pageWidth,MseConfig.pageHeight))),this.currGame.draw(a)):"LOSE"==this.state&&(a.fillStyle="#000",a.fillRect(this.getX(),this.getY(),this.width-5,this.height-5),this.losetext.draw(a),this.passBn.draw(a)))}};b.GameShower.prototype=new b.UIObject;b.GameShower.prototype.constructor=b.GameShower;
b.GameExpose=function(a,c,d){b.UIObject.call(this,a,c);this.firstShow=!1;this.game=d;this.game.setExpose(this);this.msg="";this.msginlines=[];this.font||(this.font="12px Verdana");this.lineHeight=Math.round(1.2*checkFontSize(this.font));this.evtDeleg.addListener("firstShow",new b.Callback(a.interrupt,a));this.passBn=new b.Button(this,{pos:[this.width-115,this.height-60],size:[105,35],font:"12px "+h.font,fillStyle:"#FFF"},"Je ne joue pas","aideBar");this.launchGame=function(a){this.getContainer().evtDeleg.removeListener("click",
this.launchcb);this.passBn.inObj(a.offsetX,a.offsetY)?this.endGame():this.game.start()};this.launchcb=new b.Callback(this.launchGame,this);this.endGame=function(){a.play&&a.play()};this.logic=function(){if(!this.firstShow){this.firstShow=true;this.evtDeleg.eventNotif("firstShow");this.getContainer().evtDeleg.addListener("click",this.launchcb,true)}if(this.msg!=this.game.getMsg()){this.msg=this.game.getMsg();this.msginlines.splice(0,this.msginlines.length);this.bullWidth=this.width;this.bullHeight=
0;if(!this.msg||this.msg=="")this.bullHeight=0;else{var a=b.root.ctx;a.save();a.font=this.font;for(var c=Math.floor((this.bullWidth-20)/a.measureText("A").width),d=0;d<this.msg.length;){var h=checkNextLine(a,this.msg.substr(d),c,this.bullWidth-20);this.msginlines.push(this.msg.substr(d,h));d=d+h}a.restore()}}};this.draw=function(a){a.save();a.translate(this.getX(),this.getY()+15);a.fillStyle="#000";a.fillRect(0,0,this.width,this.height-30);a.strokeStyle="rgb(188,188,188)";a.lineWidth=5;a.strokeRect(0,
-2.5,this.width,this.height-30);a.lineWidth=1;a.font=this.font;a.textBaseline="top";a.fillStyle="#FFF";for(var b=(this.height-30-this.msginlines.length*this.lineHeight)/2,c=0;c<this.msginlines.length;c++)a.fillText(this.msginlines[c],10,b+c*this.lineHeight);a.restore();a.save();this.passBn.draw(a);a.restore()}};b.GameExpose.prototype=new b.UIObject;b.GameExpose.prototype.constructor=b.GameExpose;b.Slider=function(a,c,d,e,f){f||(f=a.parent?a.parent:b.root.container);b.UIObject.call(this,f,c);f.addLayer?
f.addLayer("slider",this):f.addObject&&f.addObject(this);this.fillStyle="rgba(145,152,159, 0.7)";this.tar=a;e||(e=0);this.enScroll=!1;this.globalAlpha=this.scrollT=0;"horizontal"==d?(this.orientation="horizontal",this.setPos(this.tar.getX(),this.tar.getY()+this.tar.getHeight()+e),this.setSize(this.tar.getWidth(),10),this.loc=0,this.length=this.width):(this.orientation="vertical",this.setPos(this.tar.getX()+this.tar.getWidth()+e,this.tar.getY()),this.setSize(10,this.tar.getHeight()),this.loc=0,this.length=
this.height);this.cbScroll=new b.Callback(this.scroll,this);this.cbGest=new b.Callback(this.gestUpdate,this);this.getContainer().evtDeleg.addListener("gestureUpdate",this.cbGest,!1,this.tar);MseConfig.mobile||this.getContainer().evtDeleg.addListener("mousewheel",this.cbScroll,!1,this.tar)};extend(b.Slider,b.UIObject);g.extend(b.Slider.prototype,{show:function(){b.fadein(this,4);this.enScroll=!0;this.evtDeleg.eventNotif("show")},hide:function(){1==this.globalAlpha&&b.fadeout(this,4);this.enScroll=
!1;this.evtDeleg.eventNotif("hide")},scroll:function(a){0==this.globalAlpha&&this.show();this.scrollT=0;if("vertical"==this.orientation){if(this.tar.offy+=a.rolled,100<this.tar.offy||this.tar.offy+this.tar.getHeight()<this.tar.parent.getHeight()/2)this.tar.offy-=a.rolled}else if(this.tar.offx+=a.rolled,100<this.tar.offx||this.tar.offx+this.tar.getWidth()<this.tar.parent.getWidth()/2)this.tar.offx-=a.rolled;this.evtDeleg.eventNotif("rolling",a.rolled)},gestUpdate:function(a){4<a.listX.length&&(a.rolled=
a.listY[a.listY.length-1]-a.listY[a.listY.length-2],this.scroll(a))},logic:function(a){if(this.enScroll)if(this.scrollT+=a,600<this.scrollT)this.hide();else{if("vertical"==this.orientation)var a=this.tar.parent.getHeight(),b=this.tar.getHeight(),d=-this.tar.offy;else a=this.tar.parent.getWidth(),b=this.tar.getWidth(),d=-this.tar.offx;this.length=a*a/b;this.loc=a*d/b;this.loc+this.length>a-30?this.length=a-this.loc-30:0>this.loc&&(this.length+=this.loc,this.loc=0)}},draw:function(a){if(0!=this.globalAlpha){a.save();
this.configCtxFlex(a);a.translate(this.getX(),this.getY());a.beginPath();if("vertical"==this.orientation){var b=this.width/2;a.arc(b,this.loc+b,b,0,Math.PI,!0);a.lineTo(0,this.loc+this.length-b);a.arc(b,this.loc+this.length-b,b,Math.PI,2*Math.PI,!0);a.lineTo(this.width,this.loc+b)}else b=this.height/2,a.arc(this.loc+b,b,b,1.5*Math.PI,0.5*Math.PI,!1),a.lineTo(this.loc+l-b,0),a.arc(this.loc+l-b,b,b,0.5*Math.PI,1.5*Math.PI,!1),a.lineTo(this.loc+b,this.height);a.fill();a.restore()}}});b.Button=function(a,
c,d,e,f,j){b.UIObject.call(this,a,c);this.txt=d;this.img=e;this.setLink(f,j)};extend(b.Button,b.UIObject);g.extend(b.Button.prototype,{urlClicked:function(){i.open(this.link,"_newtab")},setLink:function(a,c){a&&(this.link=a);"url"==c&&this.getContainer().evtDeleg.addListener("click",new b.Callback(this.urlClicked,this),!0,this)},draw:function(a,c,d){this.configCtxFlex(a);a.fillStyle="rgb(255,255,255)";a.textAlign="center";a.textBaseline="middle";null==c&&(c=this.getX(),d=this.getY());var e=b.src.getSrc(this.img);
e&&a.drawImage(e,c,d,this.width,this.height);this.txt&&a.fillText(this.txt,c+this.width/2,d+this.height/2)}});b.MenuItem=function(a,c,d,e,f,j){b.UIObject.call(this,a,c);this.txt=d;this.img=e;this.zid=11;this.linkType=null!=f&&null!=j?f:"None";this.link=j;this.linkClicked=function(){switch(this.linkType){case "None":break;case "SubMenu":this.parent.subShow=this.link;var a=this.parent.subMenu[this.link],c;for(c in a)b.fadein(a[c],8);break;case "Card":this.link.evtDeleg.addListener("click",new b.Callback(b.root.revealCard,
b.root,b.root.container),!0);b.root.poseCard(this.link);break;default:b.changePage(this.link)}};a=new b.Callback(this.linkClicked,this);switch(this.linkType){case "None":break;case "SubMenu":MseConfig.mobile?b.root.evtDistributor.addListener("click",a,!0):b.root.evtDistributor.addListener("enter",a,!0);break;default:b.root.evtDistributor.addListener("click",a,!0)}this.draw=function(a){this.configCtxFlex(a);if(this.img){var c=b.src.getSrc(this.img);a.drawImage(c,this.getX(),this.getY(),this.width,
this.height)}else a.fillRect(this.getX(),this.getY(),this.width,this.height);this.txt&&a.fillText(this.txt,this.getX()+this.width/2,this.getY()+this.height/2)}};b.MenuItem.prototype=new b.UIObject;b.MenuItem.prototype.constructor=b.MenuItem;b.Menu=function(a,c,d,e){b.Layer.call(this,a,10,c);this.iwidth=d;this.iheight=e;this.ioffx=(this.width-d)/2;this.espace=20<e/2?e/2:20;this.fillStyle="rgb(145,152,159)";this.maskAlpha=0.45;this.shadow={shadowOffsetX:0,shadowOffsetY:0,shadowBlur:5,shadowColor:"rgb(67, 67, 67)"};
this.subMenu=[];this.subShow=-1;this.offx-=this.width;this.state="PRESENT";this.zonex=this.width;this.inObj=function(a,b){if(this.insideRec)var c=this.getCanvasX()-this.zonex+this.insideRec[0],d=this.getCanvasY()+this.insideRec[1],e=this.insideRec[2],h=this.insideRec[3];else c=this.getCanvasX()-this.zonex,d=this.getCanvasY(),e=2*this.getWidth(),h=2*this.getHeight();return a>c&&a<c+e&&b>d&&b<d+h?!0:!1};this.getX=function(){return(this.parent?this.parent.getX():0)+this.offx+this.zonex};this.slideInOut=
function(){switch(this.state){case "HIDE":this.name&&b.root.container.desactiveOthers(this.name);this.state="IN";break;case "PRESENT":this.name&&b.root.container.reactiveOthers(),this.state="OUT"}};this.hide=function(){this.state="HIDE";this.globalAlpha=this.zonex=0};this.addItem=function(a,c,d,e){var h=this.objList.length;"SubMenu"==d&&(e=h);a=new b.MenuItem(this,{pos:[this.ioffx,0==h?this.espace:this.objList[h-1].offy+this.iheight+this.espace],size:[this.iwidth,this.iheight]},a,c,d,e);this.addObject(a);
return a};this.addSubItem=function(a,c,d,e,g){if(this.objList[a])return c=new b.MenuItem(this,{pos:[this.width+6,this.objList[a].offy],size:[180,this.iheight],globalAlpha:0,font:"Bold 16px "+h.font,textAlign:"center",fillStyle:"#FFF",textBaseline:"middle"},c,d,e,g),this.subMenu[a]||(this.subMenu[a]=[]),this.subMenu[a].push(c),c};this.delItem=function(a){this.objList.splice(a,1)};this.delSubItem=function(a,b){this.subMenu[b]&&this.subMenu[b].splice(a,1)};this.logic=function(a){switch(this.state){case "OUT":0<
this.zonex?(this.globalAlpha-=a/500,0>this.globalAlpha&&(this.globalAlpha=0),this.zonex-=a/500*this.width):(this.state="HIDE",this.globalAlpha=0);break;case "IN":this.zonex<this.width?(this.globalAlpha+=a/500,1<this.globalAlpha&&(this.globalAlpha=1),this.zonex+=a/500*this.width):(this.state="PRESENT",this.globalAlpha=1)}};this.draw=function(a){if("HIDE"!=this.state){var b=this.maskAlpha*this.getAlpha();a.fillStyle="rgba(0,0,0,"+b+")";a.fillRect(this.getX(),this.getY(),256,this.height);this.configCtxFlex(a);
a.fillRect(this.getX(),this.getY(),this.width,this.height);for(var c in this.objList)this.objList[c].draw(a);if(0<=this.subShow)for(c in this.subMenu[this.subShow])this.subMenu[this.subShow][c].draw(a)}};this.getContainer().evtDeleg.addListener("click",new b.Callback(this.slideInOut,this),!0)};b.Menu.prototype=new b.Layer;b.Menu.prototype.constructor=b.Menu;b.Card=function(a,c,d){b.UIObject.call(this,a,c);this._layers=[];(this.ui=d)&&this.addLayer("ui",d);this.margin=[15,15,15,15];this.angle=randomInt(40)-
20;this.lw=this.width-this.margin[1]-this.margin[3];this.lh=this.height-this.margin[0]-this.margin[2]};extend(b.Card,b.UIObject);g.extend(b.Card.prototype,{addLayer:b.BaseContainer.prototype.addLayer,delLayer:b.BaseContainer.prototype.delLayer,getLayer:b.BaseContainer.prototype.getLayer,sortLayer:b.BaseContainer.prototype.sortLayer,draw:function(a){this.ui||(a.fillStyle="rgb(252,250,242)",a.fillRoundRect(this.getX(),this.getY(),this.width,this.height,20))},ptRotate:function(a,b){var d=this.getX()+
this.width/2,e=this.getY()+this.height/2,f=a-d,h=b-e,g=this.angle*Math.PI/180,i=Math.sin(g),g=Math.cos(g);return[d+(f*g+h*i),e+(-f*i+h*g)]},inObj:function(a,c){var d=this.ptRotate(a,c);return b.UIObject.prototype.inObj.call(this,d[0],d[1])?!0:!1}});b.ImageCard=function(a,c,d,e,f){b.Card.call(this,a,c,d);e&&b.src.getSrc(e)&&(this.img=e,this.legend=f);b.src.waitSrc(this.img,new b.Callback(this.init,this))};extend(b.ImageCard,b.Card);g.extend(b.ImageCard.prototype,{legendheight:35,setImage:function(a,
c){a&&b.src.getSrc(a)&&(this.img=a,this.legend=c)},init:function(){var a=this.lw,c=this.height-this.margin[0]-this.margin[2]-this.legendheight,d=b.src.getSrc(this.img),e=a/d.width,f=c/d.height,e=e<f?e:f;this.iw=d.width*e;this.ih=d.height*e;this.ix=this.margin[3]+(a-this.iw)/2;this.iy=this.margin[0]+(c-this.ih)/2},draw:function(a){a.save();a.translate(this.getX()+this.width/2,this.getY()+this.height/2);a.rotate(this.angle*Math.PI/180);a.translate(-this.width/2,-this.height/2);for(var c in this._layers)this._layers[c].draw(a);
this.ui||(a.fillStyle="rgb(252,250,242)",a.fillRoundRect(0,0,this.width,this.height,20));this.img&&(a.drawImage(b.src.getSrc(this.img),this.ix,this.iy,this.iw,this.ih),a.font="italic 12px Verdana",a.textBaseline="top",a.textAlign="center",a.fillStyle="#000",a.fillTextWrapped(this.legend,this.ix+this.iw/2,this.iy+this.ih+5,this.lw,15),a.restore())}});b.TextContent=function(a,c){b.UIObject.call(this,a,c);this.font||(this.font="14px Verdana");this.textAlign||(this.textAlign="left");this.fillStyle||(this.fillStyle=
"#000");this.textBaseline="top";this.sections=[];this.length=0};extend(b.TextContent,b.UIObject);g.extend(b.TextContent.prototype,{seplineoff:-3.5,titletextoff:5,sectionsep:12,lineHeight:18,addSection:function(a,c,d){if(!("string"!=typeof c||"string"!=typeof d)){switch(a){case "text":var e=d;break;case "link":e=new b.Button(this,{pos:[15,this.length+this.titletextoff+this.lineHeight],size:[80,this.lineHeight],font:this.font,fillStyle:"#FFF"},"Lien","wikiBar",d,"url")}this.sections.push([a,c,e]);this.configCtx(b.root.ctx);
a=wrapText(c,b.root.ctx,this.width).length;a+=wrapText(d,b.root.ctx,this.width-15).length;a=a*this.lineHeight+this.titletextoff+this.sectionsep;this.length+=a}},getHeight:function(){return this.length},draw:function(a){a.save();a.translate(this.offx,this.offy);this.configCtxFlex(a);a.lineCap="round";for(var b=0,d=0;d<this.sections.length;d++)switch(a.font="bold "+this.font,b+=a.fillTextWrapped(this.sections[d][1],0,b,this.width,this.lineHeight)+this.titletextoff,a.beginPath(),a.moveTo(0,b+this.seplineoff),
a.lineTo(this.width,b+this.seplineoff),a.stroke(),a.font=this.font,this.sections[d][0]){case "text":b+=a.fillTextWrapped(this.sections[d][2],15,b,this.width-15,this.lineHeight)+this.sectionsep;break;case "link":this.sections[d][2].draw(a,15,b),b+=this.lineHeight+this.sectionsep}a.restore()}});b.TextCard=function(a,c,d){b.Card.call(this,a,c,d);this.content=new b.TextContent(this,{pos:[this.margin[3],this.margin[0]],size:[this.lw,this.lh]});this.addLayer("content",this.content);this.slider=new b.Slider(this.content,
{},"vertical");this.slider.setPos(this.width-this.margin[1],0)};extend(b.TextCard,b.Card);g.extend(b.TextCard.prototype,{getContainer:function(){return this},addSection:function(a,b){this.content.addSection("text",a,b)},addLink:function(a,b){this.content.addSection("link",a,b)},draw:function(a){a.save();a.translate(this.getX()+this.width/2,this.getY()+this.height/2);a.rotate(this.angle*Math.PI/180);a.translate(-this.width/2,-this.height/2);this.ui||(a.fillStyle="rgb(252,250,242)",a.fillRoundRect(0,
0,this.width,this.height,20));for(var b in this._layers)this._layers[b].draw(a);a.restore()}});b.WikiLayer=function(){b.Layer.call(this,null,11,{});this.currCard=null;this.cbDragStart=new b.Callback(this.dragStart,this);this.cbDragMove=new b.Callback(this.dragMove,this);this.cbDragEnd=new b.Callback(this.dragEnd,this)};extend(b.WikiLayer,b.Layer);g.extend(b.WikiLayer.prototype,{cardw:250,cardh:320,hide:function(){var a=this.getContainer();a&&(a.evtDeleg.removeListener("gestureStart",this.cbDragStart),
a.evtDeleg.removeListener("gestureUpdate",this.cbDragMove),a.evtDeleg.removeListener("gestureEnd",this.cbDragEnd));this.parent.reactiveOthers();this.globalAlpha=0;this.parent.delLayer("wiki")},init:function(a){if(!(!a instanceof b.UIObject)){this.parent=a;this.setSize(a.getWidth(),a.getHeight());this.setPos(0,0);this.cardx=(this.width-this.cardw)/2;this.cardy=(this.height-this.cardh)/2;for(var c in this.objList)this.objList[c].setPos(this.cardx,this.cardy);a.evtDeleg.addListener("gestureStart",this.cbDragStart,
!0,this);a.evtDeleg.addListener("gestureUpdate",this.cbDragMove,!0,this);a.evtDeleg.addListener("gestureEnd",this.cbDragEnd,!0,this);a.addLayer("wiki",this);this.globalAlpha=1;a.desactiveOthers("wiki")}},addImage:function(a,c){this.addObject(new b.ImageCard(this,{size:[this.cardw,this.cardh]},null,a,c))},addTextCard:function(){this.textCard=new b.TextCard(this,{size:[this.cardw,this.cardh]},null);this.addObject(this.textCard)},addExplication:function(a,b){this.addTextCard();this.textCard.addSection(a,
b)},addLink:function(a,b){this.textCard||this.addTextCard();this.textCard.addLink(a,b)},dragStart:function(a){for(var b=this.objList.length-1;0<=b;b--)if(this.objList[b].inObj(a.offsetX,a.offsetY)){this.objList[b].evtDeleg.eventNotif("click",a)||(this.currCard=this.objList[b]);return}this.hide()},dragMove:function(a){this.currCard&&this.currCard.move(a.listX[a.listX.length-1]-a.listX[a.listX.length-2],a.listY[a.listY.length-1]-a.listY[a.listY.length-2])},dragEnd:function(){this.currCard=null}});b.PageWiki=
function(a,c,d,e,f,j){b.Layer.call(this,a,c,d);a.addLayer("content",this);var g=b.root.ctx;g.font="22px "+h.font;var i=1.2*g.measureText(e).width;this.title=new b.Button(this,{pos:[(this.width-i)/2,15],size:[i,35],font:"22px "+h.font,fillStyle:"#FFF"},e,"wikiBar");g.font="bold 14px Arial Narrow";i=1.2*g.measureText("Revenir \u00e0 l'histoire").width;this.quit=new b.Button(this,{pos:[this.width-i-30,this.height-30],size:[i,25],font:"bold 14px Arial Narrow",fillStyle:"#FFF"},"Revenir \u00e0 l'histoire",
"wikiBar");this.photos=f;this.phOff=this.width/2;this.espace=this.width/10;this.mask=new b.Mask(this,{pos:[0,0],size:[this.width,185],fillStyle:"#434343"});d.pos=[this.offx+30,this.offy+210];d.size=[this.width-60,this.height-165];this.content=new b.ArticleLayer(a,c,d,j);this.content.setSlider();this.v=0;this.setQuitTarget=function(a){this.getContainer().evtDeleg.addListener("click",new b.Callback(b.root.transition,b.root,a),!0,this.quit)};this.addPhoto=function(a){this.photos.push(a)};this.logic=
function(a){if(0!=this.v&&null!=this.photos){this.phOff+=this.v;var c=3*-this.espace,d,e;for(e in this.photos)d=b.src.getSrc(this.photos[e]),c+=100*d.width/d.height+this.espace;this.phOff>this.width/2&&(this.phOff=this.width/2);this.phOff+c<this.width/2&&(this.phOff=this.width/2-c)}this.content.logic(a)};this.draw=function(a){this.content.draw(a);this.mask.draw(a);this.title.draw(a);this.quit.draw(a);a.save();a.globalAlpha=1;a.strokeStyle="#FFF";a.fillStyle="#727272";a.translate(this.getX(),this.getY()+
65);a.fillRect(0,1,this.width,118);a.beginPath();a.moveTo(0,0);a.lineTo(this.width,0);a.moveTo(0,120);a.lineTo(this.width,120);a.stroke();if(null!=this.photos){if(0<this.photos.length)var c=this.phOff-50;var d,e,f;for(f in this.photos){e=b.src.getSrc(this.photos[f]);d=100*e.width/e.height;if(0>c){if(0<c+d){var h=-c*e.width/d;a.drawImage(e,h,0,e.width-h,e.height,0,10,d+c,100)}}else c+d>this.width?c<this.width&&a.drawImage(e,0,0,(this.width-c)*e.width/d,e.height,c,10,this.width-c,100):a.drawImage(e,
c,10,d,100);c+=d+this.espace}}a.restore()};this.onMove=function(a){var b=a.offsetX-this.getX(),a=a.offsetY-this.getY();65>=a||185<=a?this.v=0:(b-=this.width/2,this.v=30<Math.abs(b)?b/20:0)};this.getContainer().evtDeleg.addListener("move",new b.Callback(this.onMove,this),!0)};b.PageWiki.prototype=new b.Layer;b.PageWiki.prototype.constructor=b.PageWiki;b.Video=function(a,c,d){b.UIObject.call(this,a,c);this.srcs=d;this.launch=function(){b.root.video.load(d);b.root.video.show()};this.draw=function(a){a.save();
a.fillStyle="#000";a.strokeStyle="#FFF";a.lineWidth=4;a.translate(this.getX(),this.getY());a.strokeRoundRect(0,0,this.width,this.height,5);a.fillRoundRect(0,0,this.width,this.height,5);a.beginPath();a.moveTo(this.width/2-25,this.height/2-20);a.lineTo(this.width/2+25,this.height/2);a.lineTo(this.width/2-25,this.height/2+20);a.lineTo(this.width/2-25,this.height/2-20);a.fillStyle="#FFF";a.fill();a.restore()};this.getContainer().evtDeleg.addListener("click",new b.Callback(this.launch,this),!0,this)};
b.Video.prototype=new b.UIObject;b.Video.prototype.constructor=b.Video;b.Timeline=function(a,c,d,e){if(!a.initTimeline||!a.runTimeline)return null;this.src=a;if(0<c)this.tsFixed=!0,this.interval=c,this.length=null!=e?e:0;else{if(!d instanceof Array)return null;this.tsFixed=!1;this.timeprog=d;this.length=d.length}this.src.initTimeline(this);this.start=function(){this.currIndex=this.currTimestamp=0;this.inPause=this.end=!1;this.src.runTimeline();b.currTimeline=this;this.timer=this.tsFixed?setInterval("mse.currTimeline.run()",
this.interval):setTimeout("mse.currTimeline.run()",this.timeprog[this.currIndex])};this.run=function(){this.end?this.tsFixed?clearInterval(this.timer):clearTimeout(this.timer):this.inPause||(this.currTimestamp+=this.tsFixed?this.interval:this.timeprog[this.currIndex],this.currIndex++,0==this.length||this.currIndex<e?this.tsFixed?this.src.runTimeline(this.interval):(this.timer=setTimeout("mse.currTimeline.run()",this.timeprog[this.currIndex]),this.src.runTimeline(this.timeprog[this.currIndex-1])):
this.end=!0)};this.playpause=function(){this.end||(this.inPause=!this.inPause,this.inPause||(b.currTimeline!=this&&(b.currTimeline=this),this.timer=setTimeout("mse.currTimeline.run()",1200)))};this.play=function(){this.end||(this.inPause=!1,b.currTimeline!=this&&(b.currTimeline=this),this.timer=setTimeout("mse.currTimeline.run()",1200))};this.pause=function(){this.end||(this.inPause=!0)}};b.FrameAnimation=function(a,c,d,e){if(!c instanceof Array||!a instanceof b.Sprite)return null;this.sprite=a;this.seq=
c;this.rep=isNaN(d)?1:d;this.delay=e?e:0;this.active=!1;this.evtDeleg=new b.EventDelegateSystem;b.root.animations.push(this);this.start=function(){this.currFr=0;this.currRep=1;this.delayCount=this.delay;this.active=!0;this.evtDeleg.eventNotif("start")};this.stop=function(){this.currRep=this.currFr=0;this.active=!1;this.evtDeleg.eventNotif("end")};this.logic=function(){if(!this.active)return!1;if(this.currFr<this.seq.length-1)0!=this.delay?(0==this.delayCount&&(this.currFr++,this.delayCount=this.delay),
this.delayCount--):this.currFr++;else if(this.currRep<this.rep||0==this.rep)this.currRep++,this.currFr=0;else return this.active=!1,this.evtDeleg.eventNotif("end"),!0;this.sprite.curr=this.seq[this.currFr];return!1}};b.KeyFrameAnimation=function(a,c,d){if(!a instanceof b.UIObject)return mseLog("Type Error","Element isn't a Mse UI Element"),null;if(!c||!c.frame)return mseLog("Parameter Error","No frame stamp defined"),null;for(var e in c)if(c[e].length!=c.frame.length)return mseLog("Parameter Error",
"KeyFrame length not compatible with the frame stamp"),null;this.length=c.frame.length;if(2>this.length)return mseLog("Length Error","KeyFrame Length must be larger than 2"),null;if(0!=c.frame[0])return mseLog("Error","Frame start point is not 0"),null;this.duration=c.frame[this.length-1];this.element=a;this.repeat=null==d?1:d;this.map=c;this.resetAnimation();this.evtDeleg=new b.EventDelegateSystem;this.map.opacity&&(this.element.globalAlpha=0==this.map.opacity[0]?0.01:this.map.opacity[0])};b.KeyFrameAnimation.prototype=
{construction:b.KeyFrameAnimation,setNoTransition:function(){this.notransition=!0},resetAnimation:function(){this.currId=-1;this.currFr=0;this.nextKf=this.map.frame[0];this.currRp=1},start:function(){for(var a in b.root.animations)if(b.root.animations[a]==this)return;b.root.animations.push(this)},isEnd:function(){return this.currFr>this.duration&&this.currRp==this.repeat?!0:!1},logic:function(){if(this.currFr<=this.duration){if(this.currFr==this.nextKf){this.currId++;this.nextKf=this.map.frame[this.currId+
1];for(var a in this.map){var b=this.map[a][this.currId];switch(a){case "frame":continue;case "pos":this.element.setPos(b[0],b[1]);break;case "size":this.element.setSize(b[0],b[1]);break;case "opacity":this.element.globalAlpha=b;break;case "fontSize":var d=checkFontSize(this.element.font);this.element.font=this.element.font.replace(d,b.toString());break;case "scale":this.element.scale=b;break;case "spriteSeq":this.element.curr=b}}}else if(!this.notransition){var e=(this.currFr-this.map.frame[this.currId])/
(this.nextKf-this.map.frame[this.currId]);for(a in this.map)switch(b=this.map[a][this.currId],d=this.map[a][this.currId+1],a){case "frame":case "spriteSeq":continue;case "pos":var f=b[2]?this.calTrans[b[2]]?b[2]:2:2,h=this.calTrans[f](e,b[0],d[0]),b=this.calTrans[f](e,b[1],d[1]);this.element.setPos(h,b);break;case "size":f=b[2]?this.calTrans[b[2]]?b[2]:2:2;h=this.calTrans[f](e,b[0],d[0]);b=this.calTrans[f](e,b[1],d[1]);this.element.setSize(h,b);break;case "opacity":f=b[1]?this.calTrans[b[1]]?b[1]:
2:2;this.element.globalAlpha=this.calTrans[f](e,b[0]?b[0]:b,d[0]?d[0]:d);break;case "fontSize":f=b[1]?this.calTrans[b[1]]?b[1]:2:2;b=Math.floor(this.calTrans[f](e,b[0]?b[0]:b,d[0]?d[0]:d));d=checkFontSize(this.element.font);this.element.font=this.element.font.replace(d,b.toString());break;case "scale":f=b[1]?this.calTrans[b[1]]?b[1]:2:2,this.element.scale=this.calTrans[f](e,b[0]?b[0]:b,d[0]?d[0]:d)}}this.currFr++}else if(0===this.repeat||this.currRp<this.repeat)this.currRp++,this.currFr=this.currId=
0,this.nextKf=this.map.frame[1];else return this.evtDeleg.eventNotif("end"),!0;return!1},calTrans:{1:function(a,b){return b},2:function(a,b,d){return b+a*(d-b)}}};b.Animation=function(a,c,d,e,f){(this.statiq=d?!0:!1)?b.UIObject.call(this,null,{}):b.UIObject.call(this,e,f);this.objs={};this.animes=[];this.duration=a;this.repeat=c;this.state=0;this.startCb=new b.Callback(this.start,this);this.block=!1};extend(b.Animation,b.UIObject);g.extend(b.Animation.prototype,{addObj:function(a,c){c instanceof b.UIObject&&
(this.objs[a]=c,c.parent=this)},getObj:function(a){return this.objs[a]},addAnimation:function(a,c,d){if(this.objs[a]&&(a=new b.KeyFrameAnimation(this.objs[a],c,this.repeat)))d&&a.setNoTransition(),this.animes.push(a)},start:function(){this.state=1;if(this.statiq&&-1==g.inArray(this,b.root.animes)){for(var a in this.animes)this.animes[a].resetAnimation();b.root.animes.push(this)}this.evtDeleg.eventNotif("start")},pause:function(){this.state=0},logic:function(a){if(this.state)for(var b in this.animes)this.animes[b].logic(a)},
draw:function(a){for(var b in this.objs)this.objs[b].draw(a);for(var d in this.animes)if(!this.animes[d].isEnd())return!1;this.state=0;this.evtDeleg.eventNotif("end");return!0}});i.mse=b})(window,$);
(function(i,g){var b="click,doubleClick,longPress,move,swipe,gestureStart,gestureUpdate,gestureEnd,gestureSingle,keydown,keypress,keyup,scroll,swipeleft,swiperight".split(",");i.Script=function(){this.script=null;this.states={};this.expects={};this.success={};this.invoke=function(){"function"==typeof this.script?this.script.call(this):this.script instanceof i.Callback&&this.script.invoke()};this.checkConditions=function(){for(var b in this.success)if(!this.success[b])return;this.invoke()};this.conditionChanged=
function(b,g){if("everytime"==this.expects[b]||"once"==this.expects[b]&&"triggered"!=this.states[b])this.success[b]=!0,this.checkConditions();this.states[b]="string"==typeof g?g:"triggered"}};i.Script.register=function(h,m,k){var a=new i.Script,c;for(c in h){var d="c"+c;a.states[d]=h[c].initial?h[c].expect:"";a.expects[d]=h[c].expect?h[c].expect:"everytime";a.success[d]=!1;a.delay=k?k:0;var e=h[c].src;-1!=g.inArray(h[c].type,b)&&!(h[c].src instanceof i.BaseContainer)?(e=e.getContainer(),e.evtDeleg.addListener(h[c].type,
new i.Callback(a.conditionChanged,a,[d]),!1,h[c].src)):e.evtDeleg.addListener(h[c].type,new i.Callback(a.conditionChanged,a,[d]),!1)}a.script=m}})(mse,$);(function(i,g){g.Point2=function(b,g){this.x=b;this.y=g};i.crePoint2=function(b,h){return new g.Point2(b,h)}})(window,mse);function angleFor2Point(i,g){var b=0,b=Math.atan2(g.y-i.y,g.x-i.x);return Math.round(180*b/Math.PI)}function distance2Pts(i,g,b,h){return Math.sqrt(Math.pow(b-i,2)+Math.pow(h-g,2))}
function inrect(i,g,b){return i>=b[0]&&i<=b[0]+b[2]&&g>=b[1]&&g<=b[1]+b[3]?!0:!1}function xRelatRect(i,g){return i<g[0]?-1:i>=g[0]&&i<=g[0]+g[2]?0:1}function yRelatRect(i,g){return i<g[1]?-1:i>=g[1]&&i<=g[1]+g[3]?0:1}
var NPC=function(i,g,b){2>g.length&&mseLog("Array Error","Array 'course' demande minimum 2 elements");g.length!=b.length&&mseLog("Array Error","Array 'course' have to be the same size of array 'dir'");this.sprite=i;this.animes=[];this.animes.run=new mse.FrameAnimation(i,[0,1,2,3,4,5],0,5);this.animes.stand=new mse.FrameAnimation(i,[6],0,1E3);this.v=6;this.visiond=180;this.visiona=40;this.startAngle=this.visiona*Math.PI/180;this.endAngle=-this.startAngle;this.startP=crePoint2(Math.cos(this.startAngle)*
this.visiond,Math.sin(this.startAngle)*this.visiond);this.course=g;this.dir=b;this.pos=new mse.Point2(g[0].x,g[0].y);this.currStep=0;this.nextStep=1;this.direction=angleFor2Point(this.course[0],this.course[1]);0!=b[this.currStep].length?(this.currDir=0,this.tarDir=this.dir[this.currStep][this.currDir],this.state=1,this.animes.run.stop(),this.animes.stand.start()):(this.tarDir=this.direction,this.state=0,this.animes.run.start(),this.animes.stand.stop());this.logic=function(){switch(this.state){case 0:var b=
this.course[this.nextStep].x-this.pos.x,g=this.course[this.nextStep].y-this.pos.y;if(b==0)if(g<-this.v){this.pos.y=this.pos.y-this.v;break}else{if(g>this.v){this.pos.y=this.pos.y+this.v;break}}else if(b<-this.v){this.pos.x=this.pos.x-this.v;break}else if(b>this.v){this.pos.x=this.pos.x+this.v;break}this.pos=new mse.Point2(this.course[this.nextStep].x,this.course[this.nextStep].y);if(this.currStep<this.nextStep){this.currStep=this.nextStep;this.nextStep=this.nextStep==this.course.length-1?this.nextStep-
1:this.nextStep+1}else{this.currStep=this.nextStep;this.nextStep=this.nextStep==0?1:this.nextStep-1}this.state=1;this.animes.run.stop();this.animes.stand.start();if(this.dir[this.currStep].length!=0)this.tarDir=this.dir[this.currStep][this.currDir];else{this.currDir=-1;this.tarDir=angleFor2Point(this.course[this.currStep],this.course[this.nextStep])}break;case 1:b=this.tarDir-this.direction;if(b<-2)this.direction=this.direction-2;else if(b>2)this.direction=this.direction+2;else{this.direction=this.tarDir;
if(this.currDir==-1){this.currDir=this.state=0;this.animes.run.start();this.animes.stand.stop();break}if(this.currDir<this.dir[this.currStep].length-1){this.currDir++;this.tarDir=this.dir[this.currStep][this.currDir]}else{this.tarDir=angleFor2Point(this.course[this.currStep],this.course[this.nextStep]);this.currDir=-1}}}};this.draw=function(b,g,i){b.save();b.translate(g+this.pos.x,i+this.pos.y);b.rotate(this.direction*Math.PI/180);b.fillStyle="rgba(200,0,0,0.5)";b.beginPath();b.lineTo(this.startP.x,
this.startP.y);b.arc(0,0,this.visiond,this.startAngle,this.endAngle,true);b.lineTo(0,0);b.fill();b.translate(-20,-18);this.sprite.draw(b);b.restore()}},FindSimon=function(){mse.Game.call(this);this.msg={INIT:"Clique pour aider Simon \u00e0 \u00e9chapper \u00e0 la Meute.",WIN:"Bravo!!! Simon est sauv\u00e9."};this.state="INIT";mse.src.addSource("parc","Parc/Parc.jpg","img",!0);mse.src.addSource("perso_parc","Parc/personnages.png","img",!0);mse.src.addSource("notice_parc","Parc/points-persos.png","img",
!0);var i=[];i[0]=new mse.Sprite(null,{},"perso_parc",40,37,0,37,280,37);i[1]=new mse.Sprite(null,{},"perso_parc",40,37,0,74,280,37);i[2]=new mse.Sprite(null,{},"perso_parc",40,37,0,111,280,37);i[3]=new mse.Sprite(null,{},"perso_parc",40,37,0,148,280,37);var g=[[190,250,60,650],[390,250,60,650],[580,250,60,320],[640,960,60,190],[830,570,60,390],[1030,320,60,380],[1350,320,60,770],[1660,190,60,960]],b=[[190,190,450,60],[1090,320,260,60],[640,510,390,60],[1410,570,250,60],[890,700,460,60],[190,900,
640,60],[700,1090,960,60]],h=[[crePoint2(415,925),crePoint2(415,225)],[crePoint2(810,925),crePoint2(675,925),crePoint2(675,1115)],[crePoint2(1695,335),crePoint2(1695,605),crePoint2(1695,840)],[crePoint2(1060,335),crePoint2(1060,540),crePoint2(1060,735),crePoint2(1370,735)]],m=[[[180,0],[0,180]],[[90],[],[0]],[[180],[180],[180]],[[0],[180],[],[90,-90]]];this.npc=[];for(var k=0;4>k;k++)this.npc[k]=new NPC(i[k],h[k],m[k]);this.simon=new mse.Sprite(null,{},"perso_parc",40,37,0,0,280,37);this.simonrun=
new mse.FrameAnimation(this.simon,[0,1,2,3,4,5],0,7);this.simonstand=new mse.FrameAnimation(this.simon,[6],0,1E3);this.spark=0;this.init=function(){this.npc[3].v=3;this.simondir=0;this.simonrun.stop();this.simonstand.start();this.onmove=!1;this.sx=this.sy=this.sw=this.sh=this.dx=this.dy=this.dw=this.dh=0;this.sp=new mse.Point2(225,725);this.pos=new mse.Point2(this.width/2-this.sp.x,this.height/2-this.sp.y);this.disx=this.disy=0;mse.root.evtDistributor.addListener("keydown",this.movecb,!0,this);mse.root.evtDistributor.addListener("keyup",
this.moveovercb,!0,this);MseConfig.mobile&&(mse.root.evtDistributor.addListener("gestureUpdate",this.touchMovecb,!0,this),mse.root.evtDistributor.addListener("gestureEnd",this.moveovercb,!0,this))};this.draw=function(a){a.save();a.translate(this.offx,this.offy);a.beginPath();a.moveTo(0,0);a.lineTo(this.width-5,0);a.lineTo(this.width-5,this.height-5);a.lineTo(0,this.height-5);a.closePath();a.clip();a.drawImage(mse.src.getSrc("parc"),this.sx,this.sy,this.sw,this.sh,this.dx,this.dy,this.dw,this.dh);
a.save();a.translate(this.width/2,this.height/2);a.rotate(this.simondir*Math.PI/180);a.translate(-20,-18);this.simon.draw(a);a.restore();for(var b=0;4>b;b++)this.npc[b].draw(a,this.pos.x,this.pos.y);a.globalAlpha=0.7;a.drawImage(mse.src.getSrc("parc"),5,5,192,128);a.globalAlpha=1;a.fillStyle="rgb(0,200,0)";a.fillRect(4+this.sp.x/10,4+this.sp.y/10,2,2);a.fillStyle="rgba(250,230,200,0.8)";10==this.spark?(this.spark=0,a.beginPath(),a.arc(174,34,3,0,2*Math.PI,!0),a.fill()):this.spark++;a.restore()};this.logic=
function(a){0<this.pos.x?(this.sx=0,this.sw=this.width-this.pos.x,this.dx=this.pos.x):(this.sx=-this.pos.x,this.sw=this.pos.x+1920<this.width?1920+this.pos.x:this.width,this.dx=0);0<this.pos.y?(this.sy=0,this.sh=this.height-this.pos.y,this.dy=this.pos.y):(this.sy=-this.pos.y,this.sh=this.pos.y+1280<this.height?1280+this.pos.y:this.height,this.dy=0);this.dw=this.sw;this.dh=this.sh;this.pos.x+=this.disx;this.pos.y+=this.disy;this.colliDetect()&&(this.pos.x-=this.disx,this.pos.y-=this.disy);this.sp.x=
this.width/2-this.pos.x;this.sp.y=this.height/2-this.pos.y;60>=Math.abs(this.sp.x-1690)&&10>=Math.abs(this.sp.y-290)&&(mse.root.evtDistributor.removeListener("keydown",this.movecb),mse.root.evtDistributor.removeListener("keyup",this.moveoverc),MseConfig.mobile&&(mse.root.evtDistributor.removeListener("gestureUpdate",this.touchMovecb),mse.root.evtDistributor.removeListener("gestureEnd",this.moveovercb)),this.state="WIN",this.end());for(var b=0;4>b;b++){var d=this.npc[b];d.logic(a);var e=Math.round(distance2Pts(this.sp.x,
this.sp.y,d.pos.x,d.pos.y)),f=angleFor2Point(d.pos,this.sp),f=Math.abs(f-d.direction);180<f&&(f=360-f);170>=e&&f<=d.visiona&&(mse.root.evtDistributor.removeListener("keydown",this.movecb),mse.root.evtDistributor.removeListener("keyup",this.moveovercb),MseConfig.mobile&&(mse.root.evtDistributor.removeListener("gestureUpdate",this.touchMovecb),mse.root.evtDistributor.removeListener("gestureEnd",this.moveovercb)),this.lose())}};this.colliDetect=function(){for(var a=this.width/2-this.pos.x,c=this.height/
2-this.pos.y,d=0;d<g.length;d++){var e=xRelatRect(a,g[d]);if(-1==e)break;else if(0==e&&0==yRelatRect(c,g[d]))return!1}for(d=0;d<b.length&&!(e=yRelatRect(c,b[d]),-1==e);d++)if(0==e&&0==xRelatRect(a,b[d]))return!1;return!0};this.move=function(a){var b=!1;switch(a.keyCode){case __KEY_LEFT:this.disx=4;this.disy=0;this.simondir=180;b=!0;break;case __KEY_RIGHT:this.disx=-4;this.simondir=this.disy=0;b=!0;break;case __KEY_UP:this.disy=4;this.disx=0;this.simondir=-90;b=!0;break;case __KEY_DOWN:this.disy=-4,
this.disx=0,this.simondir=90,b=!0}b&&!this.onmove&&(this.onmove=!0,this.simonrun.start(),this.simonstand.stop())};this.touchMove=function(a){var b=!0,a=angleFor2Point({x:a.listX[0],y:a.listY[0]},{x:a.offsetX,y:a.offsetY});0<=a&&15>=a||0>=a&&-15<=a?(this.disx=-4,this.simondir=this.disy=0):75<=a&&105>=a?(this.disy=-4,this.disx=0,this.simondir=90):165<=a||-165>=a?(this.disx=4,this.disy=0,this.simondir=180):-75>=a&&-105<=a?(this.disy=4,this.disx=0,this.simondir=-90):b=!1;b&&!this.onmove&&(this.onmove=
!0,this.simonrun.start(),this.simonstand.stop())};this.moveover=function(){this.disy=this.disx=0;this.onmove=!1;this.simonrun.stop();this.simonstand.start()};this.movecb=new mse.Callback(this.move,this);this.moveovercb=new mse.Callback(this.moveover,this);this.touchMovecb=new mse.Callback(this.touchMove,this)};extend(FindSimon,mse.Game);
var RatGame=function(){mse.Game.call(this);this.offx=220;this.offy=0;this.width=360;this.height=600;mse.src.addSource("ratImg","rat.png","img");var i=new mse.Sprite(this,{pos:[30,this.height-80]},"ratImg",80,50,0,0,400,100),g=new mse.Sprite(this,{pos:[20,this.height-96]},"ratImg",39,34,400,0,39,34),b=new mse.Sprite(this,{pos:[45,this.height-80]},"ratImg",40,113,0,101,400,113);mse.src.addSource("sacImg","sac.png","img");var h=new mse.Image(this,{pos:[this.width-160,20],insideRec:[60,40,60,60]},"sacImg"),
m=new mse.Sprite(this,{pos:[this.width-100,175]},"sacImg",60,40,60,155,60,40),k=[0,1,2,3,4,5,6,7,8,9],a=new mse.FrameAnimation(i,k,0,2),c=new mse.FrameAnimation(b,k,0,2);this.dragStart=function(d){var e=d.offsetX-this.offx,d=d.offsetY-this.offy;30<e&&110>e&&d>this.height-80&&d<this.height-30&&(this.sit=!1,b.offx=e-20,b.offy=d-14,a.stop(),c.start())};this.dragMove=function(a){var c=a.offsetY-this.offy-14;b.offx=a.offsetX-this.offx-20;b.offy=c};this.dragEnd=function(g){var i=g.offsetX-this.offx,k=g.offsetY-
this.offy;this.sit||(h.inObj(g.offsetX,g.offsetY)?(g=new mse.KeyFrameAnimation(b,{frame:[0,25,35],pos:[[i,k],[h.offx+70,h.offy+125],[h.offx+70,h.offy+125]]},1),g.evtDeleg.addListener("end",new mse.Callback(this.end,this)),g.start(),this.droped=!0,mse.root.evtDistributor.removeListener("gestureStart",d),mse.root.evtDistributor.removeListener("gestureUpdate",e),mse.root.evtDistributor.removeListener("gestureEnd",f)):(this.sit=!0,c.stop(),a.start()))};var d=new mse.Callback(this.dragStart,this),e=new mse.Callback(this.dragMove,
this),f=new mse.Callback(this.dragEnd,this);this.init=function(){mse.root.evtDistributor.addListener("gestureStart",d,!0,this);mse.root.evtDistributor.addListener("gestureUpdate",e,!0,this);mse.root.evtDistributor.addListener("gestureEnd",f,!0,this);this.sit=!0;this.droped=!1;a.start()};this.logic=function(){if(this.droped){var a=m.offy-b.offy-114;b.fh=0>a?114+a:114;b.height=b.fh}};this.draw=function(a){h.draw(a);this.sit?(i.draw(a),g.draw(a),a.save(),a.fillStyle="#FFF",a.translate(g.getX()+1.2*g.getWidth(),
g.getY()-24),a.beginPath(),a.moveTo(-10,30),a.lineTo(0,15),a.lineTo(10,30),a.lineTo(-10,30),a.fill(),a.fillRoundRect(0,0,240,30,10),a.fillStyle="#000",a.font="20px Verdana",a.textBaseline="top",a.fillText("Aide Simon, vite!",10,4),a.restore()):b.draw(a);this.droped&&m.draw(a)}};extend(RatGame,mse.Game);var coords=JSON.parse('{"cid0":800,"cid1":600,"cid2":-1.25,"cid3":-2.5,"cid4":20,"cid5":360,"cid6":220,"cid7":0,"cid8":151.25,"cid9":188.75,"cid10":66.25,"cid11":61.25,"cid12":330,"cid13":235,"cid14":27.5,"cid15":187.5,"cid16":245,"cid17":16.5,"cid18":231.25,"cid19":181.25,"cid20":120,"cid21":141.25}');
initMseConfig();mse.init();
function createbook(){var i=new mse.Root("Test",coords.cid0,coords.cid1,"portrait"),g;mse.src.addSource("src0","./images/src0_image.jpeg","img",!0);mse.src.addSource("src1","./images/src1_image.jpeg","img",!0);mse.src.addSource("src2","./images/src2_image.jpeg","img",!0);mse.src.addSource("src3","./images/src3_image.png","img",!0);mse.src.addSource("src4","./images/src4_image.png","img",!0);g=new mse.WikiLayer;g.addImage("src3","sac");g.addTextCard();g.textCard.addSection("Sac","Sac a dos");g.textCard.addSection("like",
"jki ghjy guyghf iug tyfd");mse.src.addSource("src5","./images/src5_image.jpeg","img",!0);mse.src.addSource("src6","./images/src6_image.jpeg","img",!0);mse.src.addSource("src9","./images/src9_image.jpeg","img",!0);var b,h,m,k,a,c,d,e,f,j,n,o,r,s,t,u,v,w,x,y,z,A,B,p,C,D,q,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,da,ea,fa,ga,ha,ia,ja,ka,la,ma,na,oa,pa,qa,ra,sa,ta,ua,va,wa,xa,ya,za,Aa,Ba,Ca,Da,Ea,Fa,Ga,Ha,Ia,Ja,Ka,La,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,
jb,kb,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed;b=new mse.BaseContainer(i,{size:[coords.cid0,coords.cid1]});m=new mse.Layer(b,1,{globalAlpha:1,size:[coords.cid0,coords.cid1]});d=new mse.Image(m,{size:[coords.cid0,coords.cid1],pos:[coords.cid2,
coords.cid3],fillStyle:"rgb(0, 0, 0)",globalAlpha:1,font:"normal "+coords.cid4+"px Times",textAlign:"left"},"src5");m.addObject(d);b.addLayer("backdefault",m);k=new mse.Layer(b,2,{globalAlpha:1,size:[coords.cid0,coords.cid1]});e=new mse.Mask(k,{size:[coords.cid5,coords.cid1],pos:[coords.cid6,coords.cid7],fillStyle:"rgb(0, 0, 0)",globalAlpha:0.69,font:"normal "+coords.cid4+"px Times",textAlign:"left"});k.addObject(e);f=new mse.Image(k,{size:[coords.cid8,coords.cid9],pos:[coords.cid10,coords.cid11]},
"src4");k.addObject(f);b.addLayer("mask",k);a=new mse.ArticleLayer(b,3,{size:[coords.cid12,coords.cid1],pos:[coords.cid13,coords.cid7],fillStyle:"rgb(255, 255, 255)",globalAlpha:1,font:"normal "+coords.cid4+"px Helvetical",textAlign:"left",textBaseline:"top",lineHeight:coords.cid14},null);j=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Durant quelques instants, Simon resta ",!0);a.addObject(j);f=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"suspendu dans les airs. Une sensation ",!0);a.addObject(f);
n=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"unique, enivrante. Comme s\u2019il volait.",!0);a.addObject(n);o=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il est malade ce type !",!0);a.addObject(o);d=new FindSimon;a.addGame(d);r=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Et soudain, la chute. Interminable. ",!0);a.addObject(r);s=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il se mit \u00e0 paniquer. Devant lui, il n\u2019y ",!0);a.addObject(s);t=new mse.Text(a,{size:[coords.cid12,
coords.cid14]},"avait qu\u2019un trou noir, b\u00e9ant, une porte ",!0);a.addObject(t);u=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"de t\u00e9n\u00e8bres ouverte sur les Enfers.",!0);a.addObject(u);v=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Apr\u00e8s tout ce n\u2019\u00e9tait peut-\u00eatre pas une ",!0);a.addObject(v);w=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"bonne id\u00e9e.",!0);a.addObject(w);x=new mse.Image(a,{size:[coords.cid15,coords.cid16],pos:[coords.cid17,coords.cid4]},
"src3");a.addObject(x);y=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"On fait le tour et on le r\u00e9cup\u00e8re en bas.",!0);a.addObject(y);z=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Ce fut la derni\u00e8re chose qu\u2019il entendit ",!0);a.addObject(z);A=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"avant d\u2019atterrir avec violence dans un ",!0);a.addObject(A);B=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e9pais taillis. Le choc lui arracha un cri. ",!0);a.addObject(B);
p=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Tout son corps lui faisait mal, ses bras ",!0);p.addLink(new mse.Link("lui",16,"wiki",g));a.addObject(p);C=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"z\u00e9br\u00e9s d\u2019\u00e9corchures, le souffle ",!0);a.addObject(C);D=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u00e9finitivement coup\u00e9. ",!0);a.addObject(D);q=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il n\u2019\u00e9tait pas tomb\u00e9 sur le sol. Il \u00e9tait ",
!0);q.addLink(new mse.Link("tomb\u00e9",19,"fb","http://www.facebook.com/pandamicro"));a.addObject(q);E=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"suspendu juste au-dessus de la voie ",!0);a.addObject(E);F=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ferr\u00e9e, sauv\u00e9 par un buisson ",!0);a.addObject(F);G=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"providentiel qui poussait dans le vide. ",!0);a.addObject(G);H=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Waouh, songea-t-il en essayant de se ",
!0);a.addObject(H);I=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u00e9gager, je l\u2019ai \u00e9chapp\u00e9 belle\u2026",!0);a.addObject(I);J=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Mais, alors qu\u2019il pensait s\u2019en \u00eatre sorti, ",!0);a.addObject(J);K=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"les racines du taillis c\u00e9d\u00e8rent d\u2019un seul ",!0);a.addObject(K);L=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"coup, propulsant Simon deux m\u00e8tres ",
!0);a.addObject(L);M=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"plus bas. ",!0);a.addObject(M);N=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Ne pas atterrir sur mon sac, surtout ne ",!0);a.addObject(N);O=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"pas atterrir sur mon sac, fut sa seule ",!0);a.addObject(O);P=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"pens\u00e9e avant de rejoindre le ballast. ",!0);a.addObject(P);Q=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Les angles aigus des pierres p\u00e9n\u00e9tr\u00e8rent ",
!0);a.addObject(Q);R=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"dans ses c\u00f4tes et sa t\u00eate heurta le m\u00e9tal ",!0);a.addObject(R);S=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"de la voie abandonn\u00e9e. ",!0);a.addObject(S);T=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il \u00e9tait allong\u00e9 sur une traverse, son ",!0);a.addObject(T);U=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"regard bleu inond\u00e9 par la lueur de la ",!0);a.addObject(U);V=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"pleine lune. Il n\u2019avait plus envie de ",!0);a.addObject(V);W=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"bouger, absorb\u00e9 par les dessins ",!0);a.addObject(W);X=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"myst\u00e9rieux que tra\u00e7aient les \u00e9toiles ",!0);a.addObject(X);Y=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"dans le ciel.",!0);a.addObject(Y);Z=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Une \u00e9trange sensation \u2013 humide et ",
!0);a.addObject(Z);aa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"r\u00e2peuse \u00e0 la fois - le tira de sa r\u00eaverie. ",!0);a.addObject(aa);ba=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"C\u2019\u00e9tait la minuscule langue de Dark. ",!0);a.addObject(ba);ca=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dark ! Tu n\u2019as rien ! s\u2019exclama Simon ",!0);a.addObject(ca);da=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"en se redressant.",!0);a.addObject(da);ea=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"Aussit\u00f4t le rat se lova dans son cou, ",!0);a.addObject(ea);fa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"rassur\u00e9 \u00e0 son tour par l\u2019\u00e9tat de sant\u00e9 de ",!0);a.addObject(fa);ga=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"son ma\u00eetre.  ",!0);a.addObject(ga);ha=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il est l\u00e0. Vivant !",!0);a.addObject(ha);ia=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"La Fouine ! ",
!0);a.addObject(ia);ja=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"La Meute n\u2019avait pas mis bien ",!0);a.addObject(ja);ka=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"longtemps pour le retrouver. La traque ",!0);a.addObject(ka);la=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"allait recommencer. Mais l\u2019adolescent ",!0);a.addObject(la);ma=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e9tait fourbu, perclus de douleurs et il se ",!0);a.addObject(ma);na=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"voyait mal fuir encore une fois. ",!0);a.addObject(na);oa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il se releva, fouillant  l\u2019obscurit\u00e9 ",!0);a.addObject(oa);pa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"alentour. ",!0);a.addObject(pa);qa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"A droite, le danger...",!0);a.addObject(qa);ra=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"A gauche, l\u2019\u0153il b\u00e9ant d\u2019un tunnel ",
!0);a.addObject(ra);sa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ferroviaire qui plongeait sous le Parc.",!0);a.addObject(sa);ta=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il n\u2019y avait pas \u00e0 h\u00e9siter.",!0);a.addObject(ta);ua=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il ramassa sa besace et se remit en ",!0);a.addObject(ua);va=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"route. Il avait faim, il avait froid et sa ",!0);a.addObject(va);wa=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"cheville le faisait affreusement souffrir. ",!0);a.addObject(wa);xa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il extirpa la lampe de son sac et caressa ",!0);a.addObject(xa);ya=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"la fourrure de Dark.",!0);a.addObject(ya);za=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Eh bien, mon vieux, je crois que nous ",!0);a.addObject(za);Aa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"sommes en bien mauvaise posture. ",
!0);a.addObject(Aa);Ba=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"D\u00e9sol\u00e9 de t\u2019avoir entra\u00een\u00e9 l\u00e0-dedans. ",!0);a.addObject(Ba);Ca=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Le rongeur l\u2019\u00e9coutait d\u2019un air attentif, ",!0);a.addObject(Ca);Da=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"dress\u00e9 sur ses pattes post\u00e9rieures, le nez ",!0);a.addObject(Da);Ea=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"tendu. ",!0);a.addObject(Ea);
Fa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Voil\u00e0 que je me mets \u00e0 parler \u00e0 mon rat ",!0);a.addObject(Fa);Ga=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"comme s\u2019il comprenait quelque chose !",!0);a.addObject(Ga);Ha=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dans la p\u00e9nombre, l\u2019entr\u00e9e du tunnel ",!0);a.addObject(Ha);Ia=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ressemblait au porche d\u2019un temple ",!0);a.addObject(Ia);Ja=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"myst\u00e9rieux. ",!0);a.addObject(Ja);Ka=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Indiana Jones. ",!0);a.addObject(Ka);La=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Sauf que l\u2019adolescent ne poss\u00e9dait ni ",!0);a.addObject(La);Ma=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"chapeau, ni fouet. ",!0);a.addObject(Ma);Na=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon \u2026 Simon \u2026 Reviens\u2026",!0);a.addObject(Na);Oa=
new mse.Text(a,{size:[coords.cid12,coords.cid14]},"La voix de Kevin s\u2019\u00e9levait dans la nuit. ",!0);a.addObject(Oa);Pa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Mielleuse, sournoise. ",!0);a.addObject(Pa);Qa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon, tu as gagn\u00e9. Si tu t\u2019 rends ",!0);a.addObject(Qa);Ra=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"maintenant, j\u2019te promets qu\u2019on t\u2019fera ",!0);a.addObject(Ra);Sa=new mse.Text(a,{size:[coords.cid12,
coords.cid14]},"pas trop souffrir, ajouta-t-il en raclant la ",!0);a.addObject(Sa);Ta=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"lame de son couteau contre les pierres ",!0);a.addObject(Ta);Ua=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u2019un muret.",!0);a.addObject(Ua);Va=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Un bruit affreux, qui fit dresser les poils ",!0);a.addObject(Va);Wa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"de l\u2019adolescent. ",!0);a.addObject(Wa);
Xa=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Hors de question de tomber entre leurs ",!0);a.addObject(Xa);Ya=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"mains! Il s\u2019avan\u00e7a dans les t\u00e9n\u00e8bres du ",!0);a.addObject(Ya);Za=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"tunnel, guid\u00e9 par le minuscule halo de ",!0);a.addObject(Za);$a=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"sa lampe torche. ",!0);a.addObject($a);ab=new mse.Text(a,{size:[coords.cid12,
coords.cid14]},"La vo\u00fbte min\u00e9rale r\u00e9percutait le bruit de ",!0);a.addObject(ab);bb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ses pas. ",!0);a.addObject(bb);cb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon balaya les murs et\u2026 hurla !",!0);a.addObject(cb);db=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"L\u00e0, dans la lueur blafarde, \u00e9tait apparu ",!0);a.addObject(db);eb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"un visage. D\u00e9mesur\u00e9. Grima\u00e7ant.",
!0);a.addObject(eb);fb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Une fresque.",!0);a.addObject(fb);gb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Quel idiot ! songea-t\u2019il.",!0);a.addObject(gb);hb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"L\u2019\u0153uvre repr\u00e9sentait une cr\u00e9ature ",!0);a.addObject(hb);ib=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u00e9moniaque qui semblait vouloir ",!0);a.addObject(ib);jb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},
"d\u00e9vorer l\u2019intrus. Une sorte ",!0);a.addObject(jb);kb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u2019avertissement.",!0);a.addObject(kb);lb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Impressionn\u00e9, Simon tr\u00e9bucha et s\u2019\u00e9tala ",!0);a.addObject(lb);mb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"de tout son long. ",!0);a.addObject(mb);nb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Et merde !",!0);a.addObject(nb);ob=new mse.Text(a,{size:[coords.cid12,
coords.cid14]},"Une chute sans gravit\u00e9. Sauf que Dark, ",!0);a.addObject(ob);pb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"sans doute agac\u00e9 d\u2019\u00eatre de nouveau ",!0);a.addObject(pb);qb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ballot\u00e9, avait disparu !",!0);a.addObject(qb);rb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dark ! Dark !",!0);a.addObject(rb);sb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"L\u2019adolescent avait presque cri\u00e9. ",
!0);a.addObject(sb);tb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Les cons\u00e9quences ne se firent pas ",!0);a.addObject(tb);ub=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"attendre. ",!0);a.addObject(ub);vb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Venez les gars, il est l\u00e0 ! Tout pr\u00eat !",!0);a.addObject(vb);wb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon entendit un bruit de cavalcade ",!0);a.addObject(wb);xb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},
"dans sa direction. Il balaya la surface du ",!0);a.addObject(xb);yb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"tunnel. Mais il n\u2019y avait rien qui ",!0);a.addObject(yb);zb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ressembla \u00e0 une cachette. Pas la ",!0);a.addObject(zb);Ab=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"moindre anfractuosit\u00e9, pas le moindre ",!0);a.addObject(Ab);Bb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"bloc o\u00f9 se dissimuler. ",!0);
a.addObject(Bb);Cb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Juste la queue de Dark qui disparaissait ",!0);a.addObject(Cb);Db=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"dans le mur, quelques m\u00e8tres devant lui. ",!0);a.addObject(Db);Eb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon se pr\u00e9cipita.",!0);a.addObject(Eb);Fb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Derri\u00e8re lui, les pr\u00e9dateurs se ",!0);a.addObject(Fb);Gb=new mse.Text(a,{size:[coords.cid12,
coords.cid14]},"regroupaient.",!0);a.addObject(Gb);Hb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"On se met en ligne et on avance. Il n\u2019a ",!0);a.addObject(Hb);Ib=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"aucune chance de nous \u00e9chapper.",!0);a.addObject(Ib);Jb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Une sueur froide inondait le dos de ",!0);a.addObject(Jb);Kb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"l\u2019adolescent. La peur.",!0);a.addObject(Kb);Lb=
new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dark ?",!0);a.addObject(Lb);Mb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Un couinement, juste devant lui. ",!0);a.addObject(Mb);Nb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon s\u2019approcha et d\u00e9couvrit un trou, ",!0);a.addObject(Nb);Ob=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"de la taille de son poing, qui semblait ",!0);a.addObject(Ob);Pb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"avoir \u00e9t\u00e9 creus\u00e9 \u00e0 hauteur d\u2019homme. Le ",
!0);a.addObject(Pb);Qb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"rat l\u2019attendait l\u00e0, comme pour l\u2019inviter \u00e0 ",!0);a.addObject(Qb);Rb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"le suivre.",!0);a.addObject(Rb);Sb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Et comment veux-tu que je rentre ",!0);a.addObject(Sb);Tb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"l\u00e0-dedans ? ",!0);a.addObject(Tb);Ub=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"La Meute se rapprochait encore. ",
!0);a.addObject(Ub);Vb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Ll\u2019adolescent plongea ses mains dans ",!0);a.addObject(Vb);Wb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"l\u2019orifice et s\u2019aper\u00e7ut que les parois ",!0);a.addObject(Wb);Xb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e9taient friables. Sans doute une chati\u00e8re ",!0);a.addObject(Xb);Yb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"que l\u2019on avait dissimul\u00e9e \u00e0 la h\u00e2te. En ",
!0);a.addObject(Yb);Zb=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"quelques gestes, il d\u00e9gagea un espace ",!0);a.addObject(Zb);$b=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"suffisant pour qu\u2019il puisse s\u2019y engager. ",!0);a.addObject($b);ac=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dark, tu es un g\u00e9nie, murmura Simon en ",!0);a.addObject(ac);bc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"songeant \u00e0 cette vieille comptine que lui ",!0);a.addObject(bc);
cc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"chantait sa m\u00e8re, jadis : \u00ab Muruz\u00e9, ",!0);a.addObject(cc);dc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Troussif\u00e9e, Rassimais \u00bb. ",!0);a.addObject(dc);ec=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Des mots magiques, qu\u2019il avait mis des ",!0);a.addObject(ec);fc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"ann\u00e9es \u00e0 comprendre : \u00ab Mur us\u00e9, trou ",!0);a.addObject(fc);gc=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"s\u2019y fait, rat s\u2019y met\u2026 \u00bb.",!0);a.addObject(gc);hc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il sourit un instant puis plongea le ",!0);a.addObject(hc);ic=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"faisceau de sa lampe dans le minuscule ",!0);a.addObject(ic);jc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"passage. Impossible d\u2019en apercevoir le ",!0);a.addObject(jc);kc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},
"bout. Impossible de savoir o\u00f9 il allait. ",!0);a.addObject(kc);lc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Des bruits de pas sur le gravier, juste ",!0);a.addObject(lc);mc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"derri\u00e8re lui. Pas le choix !",!0);a.addObject(mc);nc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il se faufila entre les \u00e9troites parois, les ",!0);a.addObject(nc);oc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"bras en avant, poussant son sac. Il ",
!0);a.addObject(oc);pc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"n\u2019avait m\u00eame pas la place de ramper, ",!0);a.addObject(pc);qc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"contraint d\u2019onduler \u00e0 la mani\u00e8re d\u2019un ",!0);a.addObject(qc);rc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"serpent. ",!0);a.addObject(rc);sc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"La poussi\u00e8re l\u2019aveuglait, de la boue ",!0);a.addObject(sc);tc=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"s\u2019engouffrait dans sa bouche et il ",!0);a.addObject(tc);uc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"commen\u00e7ait \u00e0 suffoquer.",!0);a.addObject(uc);vc=new mse.Text(a,{size:[coords.cid12,coords.cid14]}," Le salaud, il essaye encore de nous ",!0);a.addObject(vc);wc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e9chapper !",!0);a.addObject(wc);xc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Rep\u00e9r\u00e9 !",!0);a.addObject(xc);
yc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"L\u2019adolescent tenta d\u2019acc\u00e9l\u00e9rer le ",!0);a.addObject(yc);zc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"mouvement. Mais plus il avan\u00e7ait, plus ",!0);a.addObject(zc);Ac=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"il avait l\u2019impression que le boyau allait ",!0);a.addObject(Ac);Bc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"l\u2019avaler, qu\u2019il allait mourir l\u00e0. Il aurait ",!0);a.addObject(Bc);
Cc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"voulu hurler mais sa cage thoracique ",!0);a.addObject(Cc);Dc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e9tait trop oppress\u00e9e.",!0);a.addObject(Dc);Ec=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Vas-y ! Suis-le ! hurlait Kevin.",!0);a.addObject(Ec);Fc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Mais\u2026",!0);a.addObject(Fc);Gc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Discute pas la Fouine, vas-y !",!0);
a.addObject(Gc);Hc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Simon tremblait, la sueur collait \u00e0 son ",!0);a.addObject(Hc);Ic=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"front tandis que l\u2019autre se faufilait d\u00e9j\u00e0 ",!0);a.addObject(Ic);Jc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"\u00e0 sa poursuite. Il \u00e9tait mince, agile et ",!0);a.addObject(Jc);Kc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"surtout il avait encore plus peur de ",!0);a.addObject(Kc);
Lc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Kevin que lui. ",!0);a.addObject(Lc);Mc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Cette fois, Simon \u00e9tait bel et bien foutu.",!0);a.addObject(Mc);Nc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Soudain, un \u00e9clair blanc le fit sursauter. ",!0);a.addObject(Nc);Oc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Une silhouette spectrale venait de ",!0);a.addObject(Oc);Pc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},
"passer entre son corps et la paroi.",!0);a.addObject(Pc);Qc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Dans les secondes qui suivirent, un ",!0);a.addObject(Qc);Rc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"hurlement \u00e9branla le tunnel. ",!0);a.addObject(Rc);Sc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Mais l\u2019adolescent n\u2019eut pas le temps de ",!0);a.addObject(Sc);Tc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"s\u2019y int\u00e9resser car il venait, enfin, de ",
!0);a.addObject(Tc);Uc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"d\u00e9boucher sur un espace plus grand. ",!0);a.addObject(Uc);Vc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Il s\u2019assit un instant pour reprendre son ",!0);a.addObject(Vc);Wc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"souffle tandis que Dark lissait ses ",!0);a.addObject(Wc);Xc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"moustaches \u00e0 ses c\u00f4t\u00e9s. Quelques ",!0);a.addObject(Xc);Yc=new mse.Text(a,
{size:[coords.cid12,coords.cid14]},"gouttes de sang poissaient son museau. ",!0);a.addObject(Yc);Zc=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Le visage de Simon s\u2019\u00e9claira : l\u2019\u00e9clair ",!0);a.addObject(Zc);$c=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"blanc, le hurlement.",!0);a.addObject($c);ad=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"Sacr\u00e9 Dark ! Sans toi, je n\u2019avais aucune ",!0);a.addObject(ad);bd=new mse.Text(a,{size:[coords.cid12,coords.cid14]},
"chance\u2026 Maintenant, la question est de ",!0);a.addObject(bd);cd=new mse.Text(a,{size:[coords.cid12,coords.cid14]},"savoir o\u00f9 nous avons atterri !",!0);a.addObject(cd);a.setDefile(1300);b.addLayer("art",a);h=new mse.BaseContainer(null,{size:[coords.cid0,coords.cid1]});c=new mse.Layer(h,1,{globalAlpha:1,size:[coords.cid0,coords.cid1]});dd=new mse.Image(c,{size:[coords.cid0,coords.cid1],pos:[coords.cid7,coords.cid7]},"src6");c.addObject(dd);ed=new mse.Image(c,{size:[coords.cid18,coords.cid19],
pos:[coords.cid20,coords.cid21]},"src9");c.addObject(ed);h.addLayer("back2default",c);mse.currTimeline.start()}mse.autoFitToWindow(createbook);
