
mse.coords = JSON.parse('{"cid0":800,"cid1":600,"cid2":300,"cid3":590,"cid4":30,"cid5":10,"cid6":15,"cid7":20,"cid8":375,"cid9":25,"cid10":216.25,"cid11":237.5}');
initMseConfig();
mse.init();
var pages={};
var layers={};
var objs={};
var animes={};
var games={};
var wikis={};
function createbook(){
	mse.configs.srcPath='./dialogue/';
	window.root = new mse.Root('dialogue',mse.coor('cid0'),mse.coor('cid1'),'portrait');
	var temp = {};
	mse.src.addSource('src0','images/src0.png','img',true);
	mse.src.addSource('src2','images/src2.png','img',true);
	pages.page=new mse.BaseContainer(root,{size:[mse.coor('cid0'),mse.coor('cid1')]});
	layers.pagedefault=new mse.Layer(pages.page,1,{"globalAlpha":1,"textBaseline":"top","size":[mse.coor('cid0'),mse.coor('cid1')]});
	pages.page.addLayer('pagedefault',layers.pagedefault);
	layers.art=new mse.ArticleLayer(pages.page,2,{"size":[mse.coor('cid2'),mse.coor('cid3')],"pos":[mse.coor('cid4'),mse.coor('cid5')],"globalAlpha":1,"font":"normal "+mse.coor('cid6')+"px Arial","textAlign":"left","textBaseline":"top","lineHeight":mse.coor('cid7')},null);
	objs.obj0=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'It is a long established fact that a reader will ',true); layers.art.addObject(objs.obj0);
	objs.obj1=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'be distracted by the readable content of a ',true); layers.art.addObject(objs.obj1);
	objs.obj28=new mse.Speaker(layers.art,{"size":[mse.coor('cid10'),mse.coor('cid9')]}, 'bodom', 'src2'); layers.art.addObject(objs.obj28);
	objs.obj29=new mse.Text(layers.art,{"size":[mse.coor('cid10'),mse.coor('cid9')]},'dfhdfh drh',true);
	objs.obj28.addObject(objs.obj29);
	objs.obj2=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'page when looking at its layout. The point of ',true); layers.art.addObject(objs.obj2);
	objs.obj25=new mse.Speaker(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]}, 'vlkdsg', ''); layers.art.addObject(objs.obj25);
	objs.obj26=new mse.Text(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]},'dgjmhn,fmkd  olfhgdf lgq',true);
	objs.obj25.addObject(objs.obj26);
	objs.obj3=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'using Lorem Ipsum is that it has a ',true); layers.art.addObject(objs.obj3);
	objs.obj4=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'more-or-less norm\'al distri\'bution of letters, as ',true); layers.art.addObject(objs.obj4);
	objs.obj5=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'opposed to using Content here, content here, ',true); layers.art.addObject(objs.obj5);
	objs.obj15=new mse.Speaker(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]}, 'florent', ''); layers.art.addObject(objs.obj15);
	objs.obj16=new mse.Text(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]},'gsfjlh',true);
	objs.obj15.addObject(objs.obj16);
	objs.obj6=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'making it look like readable English. Many ',true); layers.art.addObject(objs.obj6);
	objs.obj7=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'desktop publishing packages and web page ',true); layers.art.addObject(objs.obj7);
	objs.obj8=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'editors now use Lorem Ipsum as their default ',true); layers.art.addObject(objs.obj8);
	objs.obj9=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'model text, and a search for lorem ipsum will ',true); layers.art.addObject(objs.obj9);
	objs.obj18=new mse.Speaker(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]}, 'florent', ''); layers.art.addObject(objs.obj18);
	objs.obj19=new mse.Text(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]},'hfdh hfdh',true);
	objs.obj18.addObject(objs.obj19);
	objs.obj10=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'uncover many web sites still in their infancy. ',true); layers.art.addObject(objs.obj10);
	objs.obj11=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'Various versions have evolved over the years, ',true); layers.art.addObject(objs.obj11);
	objs.obj21=new mse.Speaker(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]}, 'florent', ''); layers.art.addObject(objs.obj21);
	objs.obj22=new mse.Text(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]},'fgkldqghid dsiulgh dsuigh ',true);
	objs.obj21.addObject(objs.obj22);
	objs.obj23=new mse.Text(layers.art,{"size":[mse.coor('cid11'),mse.coor('cid9')]},'qsdfiugh',true);
	objs.obj21.addObject(objs.obj23);
	objs.obj12=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'sometimes by accident, sometimes on ',true); layers.art.addObject(objs.obj12);
	objs.obj13=new mse.Text(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]},'purpose (injected humour and the like).',true); layers.art.addObject(objs.obj13);
	objs.obj14=new mse.UIObject(layers.art,{"size":[mse.coor('cid8'),mse.coor('cid9')]}); layers.art.addObject(objs.obj14);
	layers.art.setDefile(1300);
	temp.layerDefile=layers.art;
	pages.page.addLayer('art',layers.art);
	var action={};
	var reaction={};
	mse.currTimeline.start();};
mse.autoFitToWindow(createbook);