
mse.coords = JSON.parse('{"cid0":800,"cid1":600,"cid2":300,"cid3":10,"cid4":0,"cid5":20,"cid6":375,"cid7":25,"cid8":270,"cid9":368.28,"cid10":15}');
initMseConfig();
mse.init();
var pages={};
var layers={};
var objs={};
var animes={};
var games={};
var wikis={};
function createbook(){
	mse.configs.srcPath='./image/';
	window.root = new mse.Root('image',mse.coor('cid0'),mse.coor('cid1'),'portrait');
	var temp = {};
	pages.page1=new mse.BaseContainer(root,{size:[mse.coor('cid0'),mse.coor('cid1')]});
	layers.page1default=new mse.Layer(pages.page1,1,{"globalAlpha":1,"textBaseline":"top","size":[mse.coor('cid0'),mse.coor('cid1')]});
	pages.page1.addLayer('page1default',layers.page1default);
	layers.contenu=new mse.ArticleLayer(pages.page1,2,{"size":[mse.coor('cid2'),mse.coor('cid1')],"pos":[mse.coor('cid3'),mse.coor('cid4')],"globalAlpha":1,"font":"normal "+mse.coor('cid4')+"px ","textAlign":"left","textBaseline":"top","lineHeight":mse.coor('cid5')},null);
	objs.obj0=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'Phasellus magna magna, ultrices sed aliquet et, pretium a ',true); layers.contenu.addObject(objs.obj0);
	objs.obj1=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'urna. Nam libero urna, semper in aliquet lacinia, dictum sed ',true); layers.contenu.addObject(objs.obj1);
	objs.obj2=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'nulla. Aliquam pharetra tortor a purus dapibus consectetur. ',true); layers.contenu.addObject(objs.obj2);
	objs.obj3=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'Etiam at dui sed diam lobortis accumsan nec id justo. Curabitur ',true); layers.contenu.addObject(objs.obj3);
	objs.obj12=new mse.Image(layers.contenu,{"size":[mse.coor('cid8'),mse.coor('cid9')],"pos":[mse.coor('cid10'),mse.coor('cid5')]},'src0');
	objs.obj12.activateZoom(); layers.contenu.addObject(objs.obj12);
	objs.obj4=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'justo nisi, faucibus non placerat et, commodo eget tortor. Nam ',true); layers.contenu.addObject(objs.obj4);
	objs.obj5=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'pretium varius tincidunt. Integer sem dolor, ornare in sodales ',true); layers.contenu.addObject(objs.obj5);
	objs.obj6=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'eget, hendrerit volutpat dolor. Suspendisse ipsum metus, ',true); layers.contenu.addObject(objs.obj6);
	objs.obj7=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'condimentum et vulputate vel, egestas in risus. Cum sociis ',true); layers.contenu.addObject(objs.obj7);
	objs.obj8=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'natoque penatibus et magnis dis parturient montes, nascetur ',true); layers.contenu.addObject(objs.obj8);
	objs.obj9=new mse.Text(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]},'ridiculus mus.',true); layers.contenu.addObject(objs.obj9);
	objs.obj10=new mse.UIObject(layers.contenu,{"size":[mse.coor('cid6'),mse.coor('cid7')]}); layers.contenu.addObject(objs.obj10);
	layers.contenu.setDefile(1300);
	temp.layerDefile=layers.contenu;
	pages.page1.addLayer('contenu',layers.contenu);
	var action={};
	var reaction={};
	mse.currTimeline.start();};
mse.autoFitToWindow(createbook);